# Autogenerated wrapper script for Dex_jll for x86_64-linux-musl
export dex, webtemplates

JLLWrappers.@generate_wrapper_header("Dex")
JLLWrappers.@declare_executable_product(dex)
JLLWrappers.@declare_file_product(webtemplates)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_executable_product(
        dex,
        "bin/dex",
    )

    JLLWrappers.@init_file_product(
        webtemplates,
        "share/webtemplates.tar.gz",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
