ADD_TEST(compile_fail_bad_array_power "scripts/compile_fail" "bad/bad_array_power.ept" "-memalloc")
ADD_TEST(compile_fail_bad_flatten "scripts/compile_fail" "bad/bad_flatten.ept" "-memalloc")
ADD_TEST(compile_fail_bad_merge1 "scripts/compile_fail" "bad/bad_merge1.ept" "-memalloc")
ADD_TEST(compile_fail_bad_merge2 "scripts/compile_fail" "bad/bad_merge2.ept" "-memalloc")
ADD_TEST(compile_fail_bad_merge3 "scripts/compile_fail" "bad/bad_merge3.ept" "-memalloc")
ADD_TEST(compile_fail_bad_param_ident "scripts/compile_fail" "bad/bad_param_ident.ept" "-memalloc")
ADD_TEST(compile_fail_causality "scripts/compile_fail" "bad/causality.ept" "-memalloc")
ADD_TEST(compile_fail_clock_annot "scripts/compile_fail" "bad/clock_annot.ept" "-memalloc")
ADD_TEST(compile_fail_clock_causality "scripts/compile_fail" "bad/clock_causality.ept" "-memalloc")
ADD_TEST(compile_fail_clock_dep "scripts/compile_fail" "bad/clock_dep.ept" "-memalloc")
ADD_TEST(compile_fail_clocking "scripts/compile_fail" "bad/clocking.ept" "-memalloc")
ADD_TEST(compile_fail_flatten "scripts/compile_fail" "bad/flatten.ept" "-memalloc")
ADD_TEST(compile_fail_linear_acc "scripts/compile_fail" "bad/linear_acc.ept" "-memalloc")
ADD_TEST(compile_fail_linear_autom "scripts/compile_fail" "bad/linear_autom.ept" "-memalloc")
ADD_TEST(compile_fail_linear_causality "scripts/compile_fail" "bad/linear_causality.ept" "-memalloc")
ADD_TEST(compile_fail_linear_fun "scripts/compile_fail" "bad/linear_fun.ept" "-memalloc")
ADD_TEST(compile_fail_linear_init "scripts/compile_fail" "bad/linear_init.ept" "-memalloc")
ADD_TEST(compile_fail_linear_map "scripts/compile_fail" "bad/linear_map.ept" "-memalloc")
ADD_TEST(compile_fail_linear_mapfold "scripts/compile_fail" "bad/linear_mapfold.ept" "-memalloc")
ADD_TEST(compile_fail_side_effect "scripts/compile_fail" "bad/side_effect.ept" "-memalloc")
ADD_TEST(compile_fail_t10-initialization "scripts/compile_fail" "bad/t10-initialization.ept" "-memalloc")
ADD_TEST(compile_fail_t11-initialization "scripts/compile_fail" "bad/t11-initialization.ept" "-memalloc")
ADD_TEST(compile_fail_t12-initialization "scripts/compile_fail" "bad/t12-initialization.ept" "-memalloc")
ADD_TEST(compile_fail_t1 "scripts/compile_fail" "bad/t1.ept" "-memalloc")
ADD_TEST(compile_fail_t2 "scripts/compile_fail" "bad/t2.ept" "-memalloc")
ADD_TEST(compile_fail_t3 "scripts/compile_fail" "bad/t3.ept" "-memalloc")
ADD_TEST(compile_fail_t4 "scripts/compile_fail" "bad/t4.ept" "-memalloc")
ADD_TEST(compile_fail_t5 "scripts/compile_fail" "bad/t5.ept" "-memalloc")
ADD_TEST(compile_fail_t6 "scripts/compile_fail" "bad/t6.ept" "-memalloc")
ADD_TEST(compile_fail_t7 "scripts/compile_fail" "bad/t7.ept" "-memalloc")
ADD_TEST(compile_fail_t8-causality "scripts/compile_fail" "bad/t8-causality.ept" "-memalloc")
ADD_TEST(compile_fail_t9-initialization "scripts/compile_fail" "bad/t9-initialization.ept" "-memalloc")
ADD_TEST(compile_fail_when_merge1 "scripts/compile_fail" "bad/when_merge1.ept" "-memalloc")
ADD_TEST(compile_only_ais "scripts/compile_only" "good/ais.ept")
ADD_TEST(compile_only_alloc "scripts/compile_only" "good/alloc.ept")
ADD_TEST(compile_only_array1 "scripts/compile_only" "good/array1.ept")
ADD_TEST(compile_only_array2 "scripts/compile_only" "good/array2.ept")
ADD_TEST(compile_only_array_fill "scripts/compile_only" "good/array_fill.ept")
ADD_TEST(compile_only_array_iterators2 "scripts/compile_only" "good/array_iterators2.ept")
ADD_TEST(compile_only_array_iterators "scripts/compile_only" "good/array_iterators.ept")
ADD_TEST(compile_only_array_power "scripts/compile_only" "good/array_power.ept")
ADD_TEST(compile_only_auto_clock "scripts/compile_only" "good/auto_clock.ept")
ADD_TEST(compile_only_auto "scripts/compile_only" "good/auto.ept")
ADD_TEST(compile_only_autohiera2 "scripts/compile_only" "good/autohiera2.ept")
ADD_TEST(compile_only_autohiera3 "scripts/compile_only" "good/autohiera3.ept")
ADD_TEST(compile_only_autohiera "scripts/compile_only" "good/autohiera.ept")
ADD_TEST(compile_only_bad_updown "scripts/compile_only" "good/bad_updown.ept")
ADD_TEST(compile_only_ce "scripts/compile_only" "good/ce.ept")
ADD_TEST(compile_only_ckannot "scripts/compile_only" "good/ckannot.ept")
ADD_TEST(compile_only_clock_causality "scripts/compile_only" "good/clock_causality.ept")
ADD_TEST(compile_only_clocks "scripts/compile_only" "good/clocks.ept")
ADD_TEST(compile_only_const_record "scripts/compile_only" "good/const_record.ept")
ADD_TEST(compile_only_const_scope "scripts/compile_only" "good/const_scope.ept")
ADD_TEST(compile_only_contract_automaton "scripts/compile_only" "good/contract_automaton.ept")
ADD_TEST(compile_only_contract "scripts/compile_only" "good/contract.ept")
ADD_TEST(compile_only_convolutions "scripts/compile_only" "good/convolutions.ept")
ADD_TEST(compile_only_counter "scripts/compile_only" "good/counter.ept")
ADD_TEST(compile_only_current "scripts/compile_only" "good/current.ept")
ADD_TEST(compile_only_downscale "scripts/compile_only" "good/downscale.ept")
ADD_TEST(compile_only_fbyfby2 "scripts/compile_only" "good/fbyfby2.ept")
ADD_TEST(compile_only_foldi_arrays "scripts/compile_only" "good/foldi_arrays.ept")
ADD_TEST(compile_only_foldi "scripts/compile_only" "good/foldi.ept")
ADD_TEST(compile_only_format "scripts/compile_only" "good/format.ept")
ADD_TEST(compile_only_grosauto_clock "scripts/compile_only" "good/grosauto_clock.ept")
ADD_TEST(compile_only_hierarchie "scripts/compile_only" "good/hierarchie.ept")
ADD_TEST(compile_only_itfusion "scripts/compile_only" "good/itfusion.ept")
ADD_TEST(compile_only_linear_automata "scripts/compile_only" "good/linear_automata.ept")
ADD_TEST(compile_only_linear "scripts/compile_only" "good/linear.ept")
ADD_TEST(compile_only_linear_init "scripts/compile_only" "good/linear_init.ept")
ADD_TEST(compile_only_linear_split "scripts/compile_only" "good/linear_split.ept")
ADD_TEST(compile_only_linear_vars "scripts/compile_only" "good/linear_vars.ept")
ADD_TEST(compile_only_mapnot "scripts/compile_only" "good/mapnot.ept")
ADD_TEST(compile_only_memalloc_clocks "scripts/compile_only" "good/memalloc_clocks.ept")
ADD_TEST(compile_only_memalloc_record "scripts/compile_only" "good/memalloc_record.ept")
ADD_TEST(compile_only_memalloc_simple "scripts/compile_only" "good/memalloc_simple.ept")
ADD_TEST(compile_only_minus_pre "scripts/compile_only" "good/minus_pre.ept")
ADD_TEST(compile_only_name_clash "scripts/compile_only" "good/name_clash.ept")
ADD_TEST(compile_only_norm "scripts/compile_only" "good/norm.ept")
ADD_TEST(compile_only_or_keep "scripts/compile_only" "good/or_keep.ept")
ADD_TEST(compile_only_parametrize "scripts/compile_only" "good/parametrize.ept")
ADD_TEST(compile_only_pip "scripts/compile_only" "good/pip.ept")
ADD_TEST(compile_only_pip_slice "scripts/compile_only" "good/pip_slice.ept")
ADD_TEST(compile_only_pre_tuple "scripts/compile_only" "good/pre_tuple.ept")
ADD_TEST(compile_only_quasi "scripts/compile_only" "good/quasi.ept")
ADD_TEST(compile_only_reinit "scripts/compile_only" "good/reinit.ept")
ADD_TEST(compile_only_sampling_stateful_output2 "scripts/compile_only" "good/sampling_stateful_output2.ept")
ADD_TEST(compile_only_sampling_stateful_output "scripts/compile_only" "good/sampling_stateful_output.ept")
ADD_TEST(compile_only_side_effet "scripts/compile_only" "good/side_effet.ept")
ADD_TEST(compile_only_statics1 "scripts/compile_only" "good/statics1.ept")
ADD_TEST(compile_only_statics2 "scripts/compile_only" "good/statics2.ept")
ADD_TEST(compile_only_statics "scripts/compile_only" "good/statics.ept")
ADD_TEST(compile_only_t10 "scripts/compile_only" "good/t10.ept")
ADD_TEST(compile_only_t11 "scripts/compile_only" "good/t11.ept")
ADD_TEST(compile_only_t12 "scripts/compile_only" "good/t12.ept")
ADD_TEST(compile_only_t13 "scripts/compile_only" "good/t13.ept")
ADD_TEST(compile_only_t14 "scripts/compile_only" "good/t14.ept")
ADD_TEST(compile_only_t15 "scripts/compile_only" "good/t15.ept")
ADD_TEST(compile_only_t16 "scripts/compile_only" "good/t16.ept")
ADD_TEST(compile_only_t17 "scripts/compile_only" "good/t17.ept")
ADD_TEST(compile_only_t18 "scripts/compile_only" "good/t18.ept")
ADD_TEST(compile_only_t19 "scripts/compile_only" "good/t19.ept")
ADD_TEST(compile_only_t1 "scripts/compile_only" "good/t1.ept")
ADD_TEST(compile_only_t2 "scripts/compile_only" "good/t2.ept")
ADD_TEST(compile_only_t2open "scripts/compile_only" "good/t2open.ept")
ADD_TEST(compile_only_t3 "scripts/compile_only" "good/t3.ept")
ADD_TEST(compile_only_t4 "scripts/compile_only" "good/t4.ept")
ADD_TEST(compile_only_t5 "scripts/compile_only" "good/t5.ept")
ADD_TEST(compile_only_t6 "scripts/compile_only" "good/t6.ept")
ADD_TEST(compile_only_t7 "scripts/compile_only" "good/t7.ept")
ADD_TEST(compile_only_t8 "scripts/compile_only" "good/t8.ept")
ADD_TEST(compile_only_t9 "scripts/compile_only" "good/t9.ept")
ADD_TEST(compile_only_t "scripts/compile_only" "good/t.ept")
ADD_TEST(compile_only_test "scripts/compile_only" "good/test.ept")
ADD_TEST(compile_only_threestates "scripts/compile_only" "good/threestates.ept")
ADD_TEST(compile_only_tt "scripts/compile_only" "good/tt.ept")
ADD_TEST(compile_only_tttt "scripts/compile_only" "good/tttt.ept")
ADD_TEST(compile_only_tuple_args "scripts/compile_only" "good/tuple_args.ept")
ADD_TEST(compile_only_type_alias "scripts/compile_only" "good/type_alias.ept")
ADD_TEST(compile_only_updown "scripts/compile_only" "good/updown.ept")
ADD_TEST(compile_only_when_merge1 "scripts/compile_only" "good/when_merge1.ept")
ADD_TEST(compile_only_xor "scripts/compile_only" "good/xor.ept")
ADD_TEST(compile_gcc_run_ais "scripts/compile_gcc_run" "good/ais.ept")
ADD_TEST(compile_gcc_run_alloc "scripts/compile_gcc_run" "good/alloc.ept")
ADD_TEST(compile_gcc_run_array1 "scripts/compile_gcc_run" "good/array1.ept")
ADD_TEST(compile_gcc_run_array2 "scripts/compile_gcc_run" "good/array2.ept")
ADD_TEST(compile_gcc_run_array_fill "scripts/compile_gcc_run" "good/array_fill.ept")
ADD_TEST(compile_gcc_run_array_iterators2 "scripts/compile_gcc_run" "good/array_iterators2.ept")
ADD_TEST(compile_gcc_run_array_iterators "scripts/compile_gcc_run" "good/array_iterators.ept")
ADD_TEST(compile_gcc_run_array_power "scripts/compile_gcc_run" "good/array_power.ept")
ADD_TEST(compile_gcc_run_auto_clock "scripts/compile_gcc_run" "good/auto_clock.ept")
ADD_TEST(compile_gcc_run_auto "scripts/compile_gcc_run" "good/auto.ept")
ADD_TEST(compile_gcc_run_autohiera2 "scripts/compile_gcc_run" "good/autohiera2.ept")
ADD_TEST(compile_gcc_run_autohiera3 "scripts/compile_gcc_run" "good/autohiera3.ept")
ADD_TEST(compile_gcc_run_autohiera "scripts/compile_gcc_run" "good/autohiera.ept")
ADD_TEST(compile_gcc_run_bad_updown "scripts/compile_gcc_run" "good/bad_updown.ept")
ADD_TEST(compile_gcc_run_ce "scripts/compile_gcc_run" "good/ce.ept")
ADD_TEST(compile_gcc_run_ckannot "scripts/compile_gcc_run" "good/ckannot.ept")
ADD_TEST(compile_gcc_run_clock_causality "scripts/compile_gcc_run" "good/clock_causality.ept")
ADD_TEST(compile_gcc_run_clocks "scripts/compile_gcc_run" "good/clocks.ept")
ADD_TEST(compile_gcc_run_const_record "scripts/compile_gcc_run" "good/const_record.ept")
ADD_TEST(compile_gcc_run_const_scope "scripts/compile_gcc_run" "good/const_scope.ept")
ADD_TEST(compile_gcc_run_contract_automaton "scripts/compile_gcc_run" "good/contract_automaton.ept")
ADD_TEST(compile_gcc_run_contract "scripts/compile_gcc_run" "good/contract.ept")
ADD_TEST(compile_gcc_run_convolutions "scripts/compile_gcc_run" "good/convolutions.ept")
ADD_TEST(compile_gcc_run_counter "scripts/compile_gcc_run" "good/counter.ept")
ADD_TEST(compile_gcc_run_current "scripts/compile_gcc_run" "good/current.ept")
ADD_TEST(compile_gcc_run_downscale "scripts/compile_gcc_run" "good/downscale.ept")
ADD_TEST(compile_gcc_run_fbyfby2 "scripts/compile_gcc_run" "good/fbyfby2.ept")
ADD_TEST(compile_gcc_run_foldi_arrays "scripts/compile_gcc_run" "good/foldi_arrays.ept")
ADD_TEST(compile_gcc_run_foldi "scripts/compile_gcc_run" "good/foldi.ept")
ADD_TEST(compile_gcc_run_format "scripts/compile_gcc_run" "good/format.ept")
ADD_TEST(compile_gcc_run_grosauto_clock "scripts/compile_gcc_run" "good/grosauto_clock.ept")
ADD_TEST(compile_gcc_run_hierarchie "scripts/compile_gcc_run" "good/hierarchie.ept")
ADD_TEST(compile_gcc_run_itfusion "scripts/compile_gcc_run" "good/itfusion.ept")
ADD_TEST(compile_gcc_run_linear_automata "scripts/compile_gcc_run" "good/linear_automata.ept")
ADD_TEST(compile_gcc_run_linear "scripts/compile_gcc_run" "good/linear.ept")
ADD_TEST(compile_gcc_run_linear_init "scripts/compile_gcc_run" "good/linear_init.ept")
ADD_TEST(compile_gcc_run_linear_split "scripts/compile_gcc_run" "good/linear_split.ept")
ADD_TEST(compile_gcc_run_linear_vars "scripts/compile_gcc_run" "good/linear_vars.ept")
ADD_TEST(compile_gcc_run_mapnot "scripts/compile_gcc_run" "good/mapnot.ept")
ADD_TEST(compile_gcc_run_memalloc_clocks "scripts/compile_gcc_run" "good/memalloc_clocks.ept")
ADD_TEST(compile_gcc_run_memalloc_record "scripts/compile_gcc_run" "good/memalloc_record.ept")
ADD_TEST(compile_gcc_run_memalloc_simple "scripts/compile_gcc_run" "good/memalloc_simple.ept")
ADD_TEST(compile_gcc_run_minus_pre "scripts/compile_gcc_run" "good/minus_pre.ept")
ADD_TEST(compile_gcc_run_name_clash "scripts/compile_gcc_run" "good/name_clash.ept")
ADD_TEST(compile_gcc_run_norm "scripts/compile_gcc_run" "good/norm.ept")
ADD_TEST(compile_gcc_run_or_keep "scripts/compile_gcc_run" "good/or_keep.ept")
ADD_TEST(compile_gcc_run_parametrize "scripts/compile_gcc_run" "good/parametrize.ept")
ADD_TEST(compile_gcc_run_pip "scripts/compile_gcc_run" "good/pip.ept")
ADD_TEST(compile_gcc_run_pip_slice "scripts/compile_gcc_run" "good/pip_slice.ept")
ADD_TEST(compile_gcc_run_pre_tuple "scripts/compile_gcc_run" "good/pre_tuple.ept")
ADD_TEST(compile_gcc_run_quasi "scripts/compile_gcc_run" "good/quasi.ept")
ADD_TEST(compile_gcc_run_reinit "scripts/compile_gcc_run" "good/reinit.ept")
ADD_TEST(compile_gcc_run_sampling_stateful_output2 "scripts/compile_gcc_run" "good/sampling_stateful_output2.ept")
ADD_TEST(compile_gcc_run_sampling_stateful_output "scripts/compile_gcc_run" "good/sampling_stateful_output.ept")
ADD_TEST(compile_gcc_run_side_effet "scripts/compile_gcc_run" "good/side_effet.ept")
ADD_TEST(compile_gcc_run_statics1 "scripts/compile_gcc_run" "good/statics1.ept")
ADD_TEST(compile_gcc_run_statics2 "scripts/compile_gcc_run" "good/statics2.ept")
ADD_TEST(compile_gcc_run_statics "scripts/compile_gcc_run" "good/statics.ept")
ADD_TEST(compile_gcc_run_t10 "scripts/compile_gcc_run" "good/t10.ept")
ADD_TEST(compile_gcc_run_t11 "scripts/compile_gcc_run" "good/t11.ept")
ADD_TEST(compile_gcc_run_t12 "scripts/compile_gcc_run" "good/t12.ept")
ADD_TEST(compile_gcc_run_t13 "scripts/compile_gcc_run" "good/t13.ept")
ADD_TEST(compile_gcc_run_t14 "scripts/compile_gcc_run" "good/t14.ept")
ADD_TEST(compile_gcc_run_t15 "scripts/compile_gcc_run" "good/t15.ept")
ADD_TEST(compile_gcc_run_t16 "scripts/compile_gcc_run" "good/t16.ept")
ADD_TEST(compile_gcc_run_t17 "scripts/compile_gcc_run" "good/t17.ept")
ADD_TEST(compile_gcc_run_t18 "scripts/compile_gcc_run" "good/t18.ept")
ADD_TEST(compile_gcc_run_t19 "scripts/compile_gcc_run" "good/t19.ept")
ADD_TEST(compile_gcc_run_t1 "scripts/compile_gcc_run" "good/t1.ept")
ADD_TEST(compile_gcc_run_t2 "scripts/compile_gcc_run" "good/t2.ept")
ADD_TEST(compile_gcc_run_t2open "scripts/compile_gcc_run" "good/t2open.ept")
ADD_TEST(compile_gcc_run_t3 "scripts/compile_gcc_run" "good/t3.ept")
ADD_TEST(compile_gcc_run_t4 "scripts/compile_gcc_run" "good/t4.ept")
ADD_TEST(compile_gcc_run_t5 "scripts/compile_gcc_run" "good/t5.ept")
ADD_TEST(compile_gcc_run_t6 "scripts/compile_gcc_run" "good/t6.ept")
ADD_TEST(compile_gcc_run_t7 "scripts/compile_gcc_run" "good/t7.ept")
ADD_TEST(compile_gcc_run_t8 "scripts/compile_gcc_run" "good/t8.ept")
ADD_TEST(compile_gcc_run_t9 "scripts/compile_gcc_run" "good/t9.ept")
ADD_TEST(compile_gcc_run_t "scripts/compile_gcc_run" "good/t.ept")
ADD_TEST(compile_gcc_run_test "scripts/compile_gcc_run" "good/test.ept")
ADD_TEST(compile_gcc_run_threestates "scripts/compile_gcc_run" "good/threestates.ept")
ADD_TEST(compile_gcc_run_tt "scripts/compile_gcc_run" "good/tt.ept")
ADD_TEST(compile_gcc_run_tttt "scripts/compile_gcc_run" "good/tttt.ept")
ADD_TEST(compile_gcc_run_tuple_args "scripts/compile_gcc_run" "good/tuple_args.ept")
ADD_TEST(compile_gcc_run_type_alias "scripts/compile_gcc_run" "good/type_alias.ept")
ADD_TEST(compile_gcc_run_updown "scripts/compile_gcc_run" "good/updown.ept")
ADD_TEST(compile_gcc_run_when_merge1 "scripts/compile_gcc_run" "good/when_merge1.ept")
ADD_TEST(compile_gcc_run_xor "scripts/compile_gcc_run" "good/xor.ept")
ADD_TEST(compile_gcc_run_reset_init "scripts/compile_gcc_run" "good/reset_init.ept")
ADD_TEST(compile_gcc_run_reset_fby "scripts/compile_gcc_run" "good/reset_fby.ept")
ADD_TEST(compile_gcc_run_literals "scripts/compile_gcc_run" "good/literals.ept")
ADD_TEST(test_option_bool_ais "scripts/test_option" "good/ais.ept" "-bool")
ADD_TEST(test_option_bool_alloc "scripts/test_option" "good/alloc.ept" "-bool")
ADD_TEST(test_option_bool_array1 "scripts/test_option" "good/array1.ept" "-bool")
ADD_TEST(test_option_bool_array2 "scripts/test_option" "good/array2.ept" "-bool")
ADD_TEST(test_option_bool_array_fill "scripts/test_option" "good/array_fill.ept" "-bool")
ADD_TEST(test_option_bool_array_iterators2 "scripts/test_option" "good/array_iterators2.ept" "-bool")
ADD_TEST(test_option_bool_array_iterators "scripts/test_option" "good/array_iterators.ept" "-bool")
ADD_TEST(test_option_bool_array_power "scripts/test_option" "good/array_power.ept" "-bool")
ADD_TEST(test_option_bool_auto_clock "scripts/test_option" "good/auto_clock.ept" "-bool")
ADD_TEST(test_option_bool_auto "scripts/test_option" "good/auto.ept" "-bool")
ADD_TEST(test_option_bool_autohiera2 "scripts/test_option" "good/autohiera2.ept" "-bool")
ADD_TEST(test_option_bool_autohiera3 "scripts/test_option" "good/autohiera3.ept" "-bool")
ADD_TEST(test_option_bool_autohiera "scripts/test_option" "good/autohiera.ept" "-bool")
ADD_TEST(test_option_bool_bad_updown "scripts/test_option" "good/bad_updown.ept" "-bool")
ADD_TEST(test_option_bool_ce "scripts/test_option" "good/ce.ept" "-bool")
ADD_TEST(test_option_bool_ckannot "scripts/test_option" "good/ckannot.ept" "-bool")
ADD_TEST(test_option_bool_clock_causality "scripts/test_option" "good/clock_causality.ept" "-bool")
ADD_TEST(test_option_bool_clocks "scripts/test_option" "good/clocks.ept" "-bool")
ADD_TEST(test_option_bool_const_record "scripts/test_option" "good/const_record.ept" "-bool")
ADD_TEST(test_option_bool_const_scope "scripts/test_option" "good/const_scope.ept" "-bool")
ADD_TEST(test_option_bool_contract_automaton "scripts/test_option" "good/contract_automaton.ept" "-bool")
ADD_TEST(test_option_bool_contract "scripts/test_option" "good/contract.ept" "-bool")
ADD_TEST(test_option_bool_convolutions "scripts/test_option" "good/convolutions.ept" "-bool")
ADD_TEST(test_option_bool_counter "scripts/test_option" "good/counter.ept" "-bool")
ADD_TEST(test_option_bool_current "scripts/test_option" "good/current.ept" "-bool")
ADD_TEST(test_option_bool_downscale "scripts/test_option" "good/downscale.ept" "-bool")
ADD_TEST(test_option_bool_fbyfby2 "scripts/test_option" "good/fbyfby2.ept" "-bool")
ADD_TEST(test_option_bool_foldi_arrays "scripts/test_option" "good/foldi_arrays.ept" "-bool")
ADD_TEST(test_option_bool_foldi "scripts/test_option" "good/foldi.ept" "-bool")
ADD_TEST(test_option_bool_format "scripts/test_option" "good/format.ept" "-bool")
ADD_TEST(test_option_bool_grosauto_clock "scripts/test_option" "good/grosauto_clock.ept" "-bool")
ADD_TEST(test_option_bool_hierarchie "scripts/test_option" "good/hierarchie.ept" "-bool")
ADD_TEST(test_option_bool_itfusion "scripts/test_option" "good/itfusion.ept" "-bool")
ADD_TEST(test_option_bool_linear_automata "scripts/test_option" "good/linear_automata.ept" "-bool")
ADD_TEST(test_option_bool_linear "scripts/test_option" "good/linear.ept" "-bool")
ADD_TEST(test_option_bool_linear_init "scripts/test_option" "good/linear_init.ept" "-bool")
ADD_TEST(test_option_bool_linear_split "scripts/test_option" "good/linear_split.ept" "-bool")
ADD_TEST(test_option_bool_linear_vars "scripts/test_option" "good/linear_vars.ept" "-bool")
ADD_TEST(test_option_bool_mapnot "scripts/test_option" "good/mapnot.ept" "-bool")
ADD_TEST(test_option_bool_memalloc_clocks "scripts/test_option" "good/memalloc_clocks.ept" "-bool")
ADD_TEST(test_option_bool_memalloc_record "scripts/test_option" "good/memalloc_record.ept" "-bool")
ADD_TEST(test_option_bool_memalloc_simple "scripts/test_option" "good/memalloc_simple.ept" "-bool")
ADD_TEST(test_option_bool_minus_pre "scripts/test_option" "good/minus_pre.ept" "-bool")
ADD_TEST(test_option_bool_name_clash "scripts/test_option" "good/name_clash.ept" "-bool")
ADD_TEST(test_option_bool_norm "scripts/test_option" "good/norm.ept" "-bool")
ADD_TEST(test_option_bool_or_keep "scripts/test_option" "good/or_keep.ept" "-bool")
ADD_TEST(test_option_bool_parametrize "scripts/test_option" "good/parametrize.ept" "-bool")
ADD_TEST(test_option_bool_pip "scripts/test_option" "good/pip.ept" "-bool")
ADD_TEST(test_option_bool_pip_slice "scripts/test_option" "good/pip_slice.ept" "-bool")
ADD_TEST(test_option_bool_pre_tuple "scripts/test_option" "good/pre_tuple.ept" "-bool")
ADD_TEST(test_option_bool_quasi "scripts/test_option" "good/quasi.ept" "-bool")
ADD_TEST(test_option_bool_reinit "scripts/test_option" "good/reinit.ept" "-bool")
ADD_TEST(test_option_bool_sampling_stateful_output2 "scripts/test_option" "good/sampling_stateful_output2.ept" "-bool")
ADD_TEST(test_option_bool_sampling_stateful_output "scripts/test_option" "good/sampling_stateful_output.ept" "-bool")
ADD_TEST(test_option_bool_side_effet "scripts/test_option" "good/side_effet.ept" "-bool")
ADD_TEST(test_option_bool_statics1 "scripts/test_option" "good/statics1.ept" "-bool")
ADD_TEST(test_option_bool_statics2 "scripts/test_option" "good/statics2.ept" "-bool")
ADD_TEST(test_option_bool_statics "scripts/test_option" "good/statics.ept" "-bool")
ADD_TEST(test_option_bool_t10 "scripts/test_option" "good/t10.ept" "-bool")
ADD_TEST(test_option_bool_t11 "scripts/test_option" "good/t11.ept" "-bool")
ADD_TEST(test_option_bool_t12 "scripts/test_option" "good/t12.ept" "-bool")
ADD_TEST(test_option_bool_t13 "scripts/test_option" "good/t13.ept" "-bool")
ADD_TEST(test_option_bool_t14 "scripts/test_option" "good/t14.ept" "-bool")
ADD_TEST(test_option_bool_t15 "scripts/test_option" "good/t15.ept" "-bool")
ADD_TEST(test_option_bool_t16 "scripts/test_option" "good/t16.ept" "-bool")
ADD_TEST(test_option_bool_t17 "scripts/test_option" "good/t17.ept" "-bool")
ADD_TEST(test_option_bool_t18 "scripts/test_option" "good/t18.ept" "-bool")
ADD_TEST(test_option_bool_t19 "scripts/test_option" "good/t19.ept" "-bool")
ADD_TEST(test_option_bool_t1 "scripts/test_option" "good/t1.ept" "-bool")
ADD_TEST(test_option_bool_t2 "scripts/test_option" "good/t2.ept" "-bool")
ADD_TEST(test_option_bool_t2open "scripts/test_option" "good/t2open.ept" "-bool")
ADD_TEST(test_option_bool_t3 "scripts/test_option" "good/t3.ept" "-bool")
ADD_TEST(test_option_bool_t4 "scripts/test_option" "good/t4.ept" "-bool")
ADD_TEST(test_option_bool_t5 "scripts/test_option" "good/t5.ept" "-bool")
ADD_TEST(test_option_bool_t6 "scripts/test_option" "good/t6.ept" "-bool")
ADD_TEST(test_option_bool_t7 "scripts/test_option" "good/t7.ept" "-bool")
ADD_TEST(test_option_bool_t8 "scripts/test_option" "good/t8.ept" "-bool")
ADD_TEST(test_option_bool_t9 "scripts/test_option" "good/t9.ept" "-bool")
ADD_TEST(test_option_bool_t "scripts/test_option" "good/t.ept" "-bool")
ADD_TEST(test_option_bool_test "scripts/test_option" "good/test.ept" "-bool")
ADD_TEST(test_option_bool_threestates "scripts/test_option" "good/threestates.ept" "-bool")
ADD_TEST(test_option_bool_tt "scripts/test_option" "good/tt.ept" "-bool")
ADD_TEST(test_option_bool_tttt "scripts/test_option" "good/tttt.ept" "-bool")
ADD_TEST(test_option_bool_tuple_args "scripts/test_option" "good/tuple_args.ept" "-bool")
ADD_TEST(test_option_bool_type_alias "scripts/test_option" "good/type_alias.ept" "-bool")
ADD_TEST(test_option_bool_updown "scripts/test_option" "good/updown.ept" "-bool")
ADD_TEST(test_option_bool_when_merge1 "scripts/test_option" "good/when_merge1.ept" "-bool")
ADD_TEST(test_option_bool_xor "scripts/test_option" "good/xor.ept" "-bool")
ADD_TEST(test_option_deadcode_ais "scripts/test_option" "good/ais.ept" "-deadcode")
ADD_TEST(test_option_deadcode_alloc "scripts/test_option" "good/alloc.ept" "-deadcode")
ADD_TEST(test_option_deadcode_array1 "scripts/test_option" "good/array1.ept" "-deadcode")
ADD_TEST(test_option_deadcode_array2 "scripts/test_option" "good/array2.ept" "-deadcode")
ADD_TEST(test_option_deadcode_array_fill "scripts/test_option" "good/array_fill.ept" "-deadcode")
ADD_TEST(test_option_deadcode_array_iterators2 "scripts/test_option" "good/array_iterators2.ept" "-deadcode")
ADD_TEST(test_option_deadcode_array_iterators "scripts/test_option" "good/array_iterators.ept" "-deadcode")
ADD_TEST(test_option_deadcode_array_power "scripts/test_option" "good/array_power.ept" "-deadcode")
ADD_TEST(test_option_deadcode_auto_clock "scripts/test_option" "good/auto_clock.ept" "-deadcode")
ADD_TEST(test_option_deadcode_auto "scripts/test_option" "good/auto.ept" "-deadcode")
ADD_TEST(test_option_deadcode_autohiera2 "scripts/test_option" "good/autohiera2.ept" "-deadcode")
ADD_TEST(test_option_deadcode_autohiera3 "scripts/test_option" "good/autohiera3.ept" "-deadcode")
ADD_TEST(test_option_deadcode_autohiera "scripts/test_option" "good/autohiera.ept" "-deadcode")
ADD_TEST(test_option_deadcode_bad_updown "scripts/test_option" "good/bad_updown.ept" "-deadcode")
ADD_TEST(test_option_deadcode_ce "scripts/test_option" "good/ce.ept" "-deadcode")
ADD_TEST(test_option_deadcode_ckannot "scripts/test_option" "good/ckannot.ept" "-deadcode")
ADD_TEST(test_option_deadcode_clock_causality "scripts/test_option" "good/clock_causality.ept" "-deadcode")
ADD_TEST(test_option_deadcode_clocks "scripts/test_option" "good/clocks.ept" "-deadcode")
ADD_TEST(test_option_deadcode_const_record "scripts/test_option" "good/const_record.ept" "-deadcode")
ADD_TEST(test_option_deadcode_const_scope "scripts/test_option" "good/const_scope.ept" "-deadcode")
ADD_TEST(test_option_deadcode_contract_automaton "scripts/test_option" "good/contract_automaton.ept" "-deadcode")
ADD_TEST(test_option_deadcode_contract "scripts/test_option" "good/contract.ept" "-deadcode")
ADD_TEST(test_option_deadcode_convolutions "scripts/test_option" "good/convolutions.ept" "-deadcode")
ADD_TEST(test_option_deadcode_counter "scripts/test_option" "good/counter.ept" "-deadcode")
ADD_TEST(test_option_deadcode_current "scripts/test_option" "good/current.ept" "-deadcode")
ADD_TEST(test_option_deadcode_downscale "scripts/test_option" "good/downscale.ept" "-deadcode")
ADD_TEST(test_option_deadcode_fbyfby2 "scripts/test_option" "good/fbyfby2.ept" "-deadcode")
ADD_TEST(test_option_deadcode_foldi_arrays "scripts/test_option" "good/foldi_arrays.ept" "-deadcode")
ADD_TEST(test_option_deadcode_foldi "scripts/test_option" "good/foldi.ept" "-deadcode")
ADD_TEST(test_option_deadcode_format "scripts/test_option" "good/format.ept" "-deadcode")
ADD_TEST(test_option_deadcode_grosauto_clock "scripts/test_option" "good/grosauto_clock.ept" "-deadcode")
ADD_TEST(test_option_deadcode_hierarchie "scripts/test_option" "good/hierarchie.ept" "-deadcode")
ADD_TEST(test_option_deadcode_itfusion "scripts/test_option" "good/itfusion.ept" "-deadcode")
ADD_TEST(test_option_deadcode_linear_automata "scripts/test_option" "good/linear_automata.ept" "-deadcode")
ADD_TEST(test_option_deadcode_linear "scripts/test_option" "good/linear.ept" "-deadcode")
ADD_TEST(test_option_deadcode_linear_init "scripts/test_option" "good/linear_init.ept" "-deadcode")
ADD_TEST(test_option_deadcode_linear_split "scripts/test_option" "good/linear_split.ept" "-deadcode")
ADD_TEST(test_option_deadcode_linear_vars "scripts/test_option" "good/linear_vars.ept" "-deadcode")
ADD_TEST(test_option_deadcode_mapnot "scripts/test_option" "good/mapnot.ept" "-deadcode")
ADD_TEST(test_option_deadcode_memalloc_clocks "scripts/test_option" "good/memalloc_clocks.ept" "-deadcode")
ADD_TEST(test_option_deadcode_memalloc_record "scripts/test_option" "good/memalloc_record.ept" "-deadcode")
ADD_TEST(test_option_deadcode_memalloc_simple "scripts/test_option" "good/memalloc_simple.ept" "-deadcode")
ADD_TEST(test_option_deadcode_minus_pre "scripts/test_option" "good/minus_pre.ept" "-deadcode")
ADD_TEST(test_option_deadcode_name_clash "scripts/test_option" "good/name_clash.ept" "-deadcode")
ADD_TEST(test_option_deadcode_norm "scripts/test_option" "good/norm.ept" "-deadcode")
ADD_TEST(test_option_deadcode_or_keep "scripts/test_option" "good/or_keep.ept" "-deadcode")
ADD_TEST(test_option_deadcode_parametrize "scripts/test_option" "good/parametrize.ept" "-deadcode")
ADD_TEST(test_option_deadcode_pip "scripts/test_option" "good/pip.ept" "-deadcode")
ADD_TEST(test_option_deadcode_pip_slice "scripts/test_option" "good/pip_slice.ept" "-deadcode")
ADD_TEST(test_option_deadcode_pre_tuple "scripts/test_option" "good/pre_tuple.ept" "-deadcode")
ADD_TEST(test_option_deadcode_quasi "scripts/test_option" "good/quasi.ept" "-deadcode")
ADD_TEST(test_option_deadcode_reinit "scripts/test_option" "good/reinit.ept" "-deadcode")
ADD_TEST(test_option_deadcode_sampling_stateful_output2 "scripts/test_option" "good/sampling_stateful_output2.ept" "-deadcode")
ADD_TEST(test_option_deadcode_sampling_stateful_output "scripts/test_option" "good/sampling_stateful_output.ept" "-deadcode")
ADD_TEST(test_option_deadcode_side_effet "scripts/test_option" "good/side_effet.ept" "-deadcode")
ADD_TEST(test_option_deadcode_statics1 "scripts/test_option" "good/statics1.ept" "-deadcode")
ADD_TEST(test_option_deadcode_statics2 "scripts/test_option" "good/statics2.ept" "-deadcode")
ADD_TEST(test_option_deadcode_statics "scripts/test_option" "good/statics.ept" "-deadcode")
ADD_TEST(test_option_deadcode_t10 "scripts/test_option" "good/t10.ept" "-deadcode")
ADD_TEST(test_option_deadcode_t11 "scripts/test_option" "good/t11.ept" "-deadcode")
ADD_TEST(test_option_deadcode_t12 "scripts/test_option" "good/t12.ept" "-deadcode")
ADD_TEST(test_option_deadcode_t13 "scripts/test_option" "good/t13.ept" "-deadcode")
ADD_TEST(test_option_deadcode_t14 "scripts/test_option" "good/t14.ept" "-deadcode")
ADD_TEST(test_option_deadcode_t15 "scripts/test_option" "good/t15.ept" "-deadcode")
ADD_TEST(test_option_deadcode_t16 "scripts/test_option" "good/t16.ept" "-deadcode")
ADD_TEST(test_option_deadcode_t17 "scripts/test_option" "good/t17.ept" "-deadcode")
ADD_TEST(test_option_deadcode_t18 "scripts/test_option" "good/t18.ept" "-deadcode")
ADD_TEST(test_option_deadcode_t19 "scripts/test_option" "good/t19.ept" "-deadcode")
ADD_TEST(test_option_deadcode_t1 "scripts/test_option" "good/t1.ept" "-deadcode")
ADD_TEST(test_option_deadcode_t2 "scripts/test_option" "good/t2.ept" "-deadcode")
ADD_TEST(test_option_deadcode_t2open "scripts/test_option" "good/t2open.ept" "-deadcode")
ADD_TEST(test_option_deadcode_t3 "scripts/test_option" "good/t3.ept" "-deadcode")
ADD_TEST(test_option_deadcode_t4 "scripts/test_option" "good/t4.ept" "-deadcode")
ADD_TEST(test_option_deadcode_t5 "scripts/test_option" "good/t5.ept" "-deadcode")
ADD_TEST(test_option_deadcode_t6 "scripts/test_option" "good/t6.ept" "-deadcode")
ADD_TEST(test_option_deadcode_t7 "scripts/test_option" "good/t7.ept" "-deadcode")
ADD_TEST(test_option_deadcode_t8 "scripts/test_option" "good/t8.ept" "-deadcode")
ADD_TEST(test_option_deadcode_t9 "scripts/test_option" "good/t9.ept" "-deadcode")
ADD_TEST(test_option_deadcode_t "scripts/test_option" "good/t.ept" "-deadcode")
ADD_TEST(test_option_deadcode_test "scripts/test_option" "good/test.ept" "-deadcode")
ADD_TEST(test_option_deadcode_threestates "scripts/test_option" "good/threestates.ept" "-deadcode")
ADD_TEST(test_option_deadcode_tt "scripts/test_option" "good/tt.ept" "-deadcode")
ADD_TEST(test_option_deadcode_tttt "scripts/test_option" "good/tttt.ept" "-deadcode")
ADD_TEST(test_option_deadcode_tuple_args "scripts/test_option" "good/tuple_args.ept" "-deadcode")
ADD_TEST(test_option_deadcode_type_alias "scripts/test_option" "good/type_alias.ept" "-deadcode")
ADD_TEST(test_option_deadcode_updown "scripts/test_option" "good/updown.ept" "-deadcode")
ADD_TEST(test_option_deadcode_when_merge1 "scripts/test_option" "good/when_merge1.ept" "-deadcode")
ADD_TEST(test_option_deadcode_xor "scripts/test_option" "good/xor.ept" "-deadcode")
ADD_TEST(test_option_tomato_ais "scripts/test_option" "good/ais.ept" "-tomato")
ADD_TEST(test_option_tomato_alloc "scripts/test_option" "good/alloc.ept" "-tomato")
ADD_TEST(test_option_tomato_array1 "scripts/test_option" "good/array1.ept" "-tomato")
ADD_TEST(test_option_tomato_array2 "scripts/test_option" "good/array2.ept" "-tomato")
ADD_TEST(test_option_tomato_array_fill "scripts/test_option" "good/array_fill.ept" "-tomato")
ADD_TEST(test_option_tomato_array_iterators2 "scripts/test_option" "good/array_iterators2.ept" "-tomato")
ADD_TEST(test_option_tomato_array_iterators "scripts/test_option" "good/array_iterators.ept" "-tomato")
ADD_TEST(test_option_tomato_array_power "scripts/test_option" "good/array_power.ept" "-tomato")
ADD_TEST(test_option_tomato_auto_clock "scripts/test_option" "good/auto_clock.ept" "-tomato")
ADD_TEST(test_option_tomato_auto "scripts/test_option" "good/auto.ept" "-tomato")
ADD_TEST(test_option_tomato_autohiera2 "scripts/test_option" "good/autohiera2.ept" "-tomato")
ADD_TEST(test_option_tomato_autohiera3 "scripts/test_option" "good/autohiera3.ept" "-tomato")
ADD_TEST(test_option_tomato_autohiera "scripts/test_option" "good/autohiera.ept" "-tomato")
ADD_TEST(test_option_tomato_bad_updown "scripts/test_option" "good/bad_updown.ept" "-tomato")
ADD_TEST(test_option_tomato_ce "scripts/test_option" "good/ce.ept" "-tomato")
ADD_TEST(test_option_tomato_ckannot "scripts/test_option" "good/ckannot.ept" "-tomato")
ADD_TEST(test_option_tomato_clock_causality "scripts/test_option" "good/clock_causality.ept" "-tomato")
ADD_TEST(test_option_tomato_clocks "scripts/test_option" "good/clocks.ept" "-tomato")
ADD_TEST(test_option_tomato_const_record "scripts/test_option" "good/const_record.ept" "-tomato")
ADD_TEST(test_option_tomato_const_scope "scripts/test_option" "good/const_scope.ept" "-tomato")
ADD_TEST(test_option_tomato_contract_automaton "scripts/test_option" "good/contract_automaton.ept" "-tomato")
ADD_TEST(test_option_tomato_contract "scripts/test_option" "good/contract.ept" "-tomato")
ADD_TEST(test_option_tomato_convolutions "scripts/test_option" "good/convolutions.ept" "-tomato")
ADD_TEST(test_option_tomato_counter "scripts/test_option" "good/counter.ept" "-tomato")
ADD_TEST(test_option_tomato_current "scripts/test_option" "good/current.ept" "-tomato")
ADD_TEST(test_option_tomato_downscale "scripts/test_option" "good/downscale.ept" "-tomato")
ADD_TEST(test_option_tomato_fbyfby2 "scripts/test_option" "good/fbyfby2.ept" "-tomato")
ADD_TEST(test_option_tomato_foldi_arrays "scripts/test_option" "good/foldi_arrays.ept" "-tomato")
ADD_TEST(test_option_tomato_foldi "scripts/test_option" "good/foldi.ept" "-tomato")
ADD_TEST(test_option_tomato_format "scripts/test_option" "good/format.ept" "-tomato")
ADD_TEST(test_option_tomato_grosauto_clock "scripts/test_option" "good/grosauto_clock.ept" "-tomato")
ADD_TEST(test_option_tomato_hierarchie "scripts/test_option" "good/hierarchie.ept" "-tomato")
ADD_TEST(test_option_tomato_itfusion "scripts/test_option" "good/itfusion.ept" "-tomato")
ADD_TEST(test_option_tomato_linear_automata "scripts/test_option" "good/linear_automata.ept" "-tomato")
ADD_TEST(test_option_tomato_linear "scripts/test_option" "good/linear.ept" "-tomato")
ADD_TEST(test_option_tomato_linear_init "scripts/test_option" "good/linear_init.ept" "-tomato")
ADD_TEST(test_option_tomato_linear_split "scripts/test_option" "good/linear_split.ept" "-tomato")
ADD_TEST(test_option_tomato_linear_vars "scripts/test_option" "good/linear_vars.ept" "-tomato")
ADD_TEST(test_option_tomato_mapnot "scripts/test_option" "good/mapnot.ept" "-tomato")
ADD_TEST(test_option_tomato_memalloc_clocks "scripts/test_option" "good/memalloc_clocks.ept" "-tomato")
ADD_TEST(test_option_tomato_memalloc_record "scripts/test_option" "good/memalloc_record.ept" "-tomato")
ADD_TEST(test_option_tomato_memalloc_simple "scripts/test_option" "good/memalloc_simple.ept" "-tomato")
ADD_TEST(test_option_tomato_minus_pre "scripts/test_option" "good/minus_pre.ept" "-tomato")
ADD_TEST(test_option_tomato_name_clash "scripts/test_option" "good/name_clash.ept" "-tomato")
ADD_TEST(test_option_tomato_norm "scripts/test_option" "good/norm.ept" "-tomato")
ADD_TEST(test_option_tomato_or_keep "scripts/test_option" "good/or_keep.ept" "-tomato")
ADD_TEST(test_option_tomato_parametrize "scripts/test_option" "good/parametrize.ept" "-tomato")
ADD_TEST(test_option_tomato_pip "scripts/test_option" "good/pip.ept" "-tomato")
ADD_TEST(test_option_tomato_pip_slice "scripts/test_option" "good/pip_slice.ept" "-tomato")
ADD_TEST(test_option_tomato_pre_tuple "scripts/test_option" "good/pre_tuple.ept" "-tomato")
ADD_TEST(test_option_tomato_quasi "scripts/test_option" "good/quasi.ept" "-tomato")
ADD_TEST(test_option_tomato_reinit "scripts/test_option" "good/reinit.ept" "-tomato")
ADD_TEST(test_option_tomato_sampling_stateful_output2 "scripts/test_option" "good/sampling_stateful_output2.ept" "-tomato")
ADD_TEST(test_option_tomato_sampling_stateful_output "scripts/test_option" "good/sampling_stateful_output.ept" "-tomato")
ADD_TEST(test_option_tomato_side_effet "scripts/test_option" "good/side_effet.ept" "-tomato")
ADD_TEST(test_option_tomato_statics1 "scripts/test_option" "good/statics1.ept" "-tomato")
ADD_TEST(test_option_tomato_statics2 "scripts/test_option" "good/statics2.ept" "-tomato")
ADD_TEST(test_option_tomato_statics "scripts/test_option" "good/statics.ept" "-tomato")
ADD_TEST(test_option_tomato_t10 "scripts/test_option" "good/t10.ept" "-tomato")
ADD_TEST(test_option_tomato_t11 "scripts/test_option" "good/t11.ept" "-tomato")
ADD_TEST(test_option_tomato_t12 "scripts/test_option" "good/t12.ept" "-tomato")
ADD_TEST(test_option_tomato_t13 "scripts/test_option" "good/t13.ept" "-tomato")
ADD_TEST(test_option_tomato_t14 "scripts/test_option" "good/t14.ept" "-tomato")
ADD_TEST(test_option_tomato_t15 "scripts/test_option" "good/t15.ept" "-tomato")
ADD_TEST(test_option_tomato_t16 "scripts/test_option" "good/t16.ept" "-tomato")
ADD_TEST(test_option_tomato_t17 "scripts/test_option" "good/t17.ept" "-tomato")
ADD_TEST(test_option_tomato_t18 "scripts/test_option" "good/t18.ept" "-tomato")
ADD_TEST(test_option_tomato_t19 "scripts/test_option" "good/t19.ept" "-tomato")
ADD_TEST(test_option_tomato_t1 "scripts/test_option" "good/t1.ept" "-tomato")
ADD_TEST(test_option_tomato_t2 "scripts/test_option" "good/t2.ept" "-tomato")
ADD_TEST(test_option_tomato_t2open "scripts/test_option" "good/t2open.ept" "-tomato")
ADD_TEST(test_option_tomato_t3 "scripts/test_option" "good/t3.ept" "-tomato")
ADD_TEST(test_option_tomato_t4 "scripts/test_option" "good/t4.ept" "-tomato")
ADD_TEST(test_option_tomato_t5 "scripts/test_option" "good/t5.ept" "-tomato")
ADD_TEST(test_option_tomato_t6 "scripts/test_option" "good/t6.ept" "-tomato")
ADD_TEST(test_option_tomato_t7 "scripts/test_option" "good/t7.ept" "-tomato")
ADD_TEST(test_option_tomato_t8 "scripts/test_option" "good/t8.ept" "-tomato")
ADD_TEST(test_option_tomato_t9 "scripts/test_option" "good/t9.ept" "-tomato")
ADD_TEST(test_option_tomato_t "scripts/test_option" "good/t.ept" "-tomato")
ADD_TEST(test_option_tomato_test "scripts/test_option" "good/test.ept" "-tomato")
ADD_TEST(test_option_tomato_threestates "scripts/test_option" "good/threestates.ept" "-tomato")
ADD_TEST(test_option_tomato_tt "scripts/test_option" "good/tt.ept" "-tomato")
ADD_TEST(test_option_tomato_tttt "scripts/test_option" "good/tttt.ept" "-tomato")
ADD_TEST(test_option_tomato_tuple_args "scripts/test_option" "good/tuple_args.ept" "-tomato")
ADD_TEST(test_option_tomato_type_alias "scripts/test_option" "good/type_alias.ept" "-tomato")
ADD_TEST(test_option_tomato_updown "scripts/test_option" "good/updown.ept" "-tomato")
ADD_TEST(test_option_tomato_when_merge1 "scripts/test_option" "good/when_merge1.ept" "-tomato")
ADD_TEST(test_option_tomato_xor "scripts/test_option" "good/xor.ept" "-tomato")
ADD_TEST(test_option_flatten_ais "scripts/test_option" "good/ais.ept" "-flatten")
ADD_TEST(test_option_flatten_alloc "scripts/test_option" "good/alloc.ept" "-flatten")
ADD_TEST(test_option_flatten_array1 "scripts/test_option" "good/array1.ept" "-flatten")
ADD_TEST(test_option_flatten_array2 "scripts/test_option" "good/array2.ept" "-flatten")
ADD_TEST(test_option_flatten_array_fill "scripts/test_option" "good/array_fill.ept" "-flatten")
ADD_TEST(test_option_flatten_array_iterators2 "scripts/test_option" "good/array_iterators2.ept" "-flatten")
ADD_TEST(test_option_flatten_array_iterators "scripts/test_option" "good/array_iterators.ept" "-flatten")
ADD_TEST(test_option_flatten_array_power "scripts/test_option" "good/array_power.ept" "-flatten")
ADD_TEST(test_option_flatten_auto_clock "scripts/test_option" "good/auto_clock.ept" "-flatten")
ADD_TEST(test_option_flatten_auto "scripts/test_option" "good/auto.ept" "-flatten")
ADD_TEST(test_option_flatten_autohiera2 "scripts/test_option" "good/autohiera2.ept" "-flatten")
ADD_TEST(test_option_flatten_autohiera3 "scripts/test_option" "good/autohiera3.ept" "-flatten")
ADD_TEST(test_option_flatten_autohiera "scripts/test_option" "good/autohiera.ept" "-flatten")
ADD_TEST(test_option_flatten_bad_updown "scripts/test_option" "good/bad_updown.ept" "-flatten")
ADD_TEST(test_option_flatten_ce "scripts/test_option" "good/ce.ept" "-flatten")
ADD_TEST(test_option_flatten_ckannot "scripts/test_option" "good/ckannot.ept" "-flatten")
ADD_TEST(test_option_flatten_clock_causality "scripts/test_option" "good/clock_causality.ept" "-flatten")
ADD_TEST(test_option_flatten_clocks "scripts/test_option" "good/clocks.ept" "-flatten")
ADD_TEST(test_option_flatten_const_record "scripts/test_option" "good/const_record.ept" "-flatten")
ADD_TEST(test_option_flatten_const_scope "scripts/test_option" "good/const_scope.ept" "-flatten")
ADD_TEST(test_option_flatten_contract_automaton "scripts/test_option" "good/contract_automaton.ept" "-flatten")
ADD_TEST(test_option_flatten_contract "scripts/test_option" "good/contract.ept" "-flatten")
ADD_TEST(test_option_flatten_convolutions "scripts/test_option" "good/convolutions.ept" "-flatten")
ADD_TEST(test_option_flatten_counter "scripts/test_option" "good/counter.ept" "-flatten")
ADD_TEST(test_option_flatten_current "scripts/test_option" "good/current.ept" "-flatten")
ADD_TEST(test_option_flatten_downscale "scripts/test_option" "good/downscale.ept" "-flatten")
ADD_TEST(test_option_flatten_fbyfby2 "scripts/test_option" "good/fbyfby2.ept" "-flatten")
ADD_TEST(test_option_flatten_foldi_arrays "scripts/test_option" "good/foldi_arrays.ept" "-flatten")
ADD_TEST(test_option_flatten_foldi "scripts/test_option" "good/foldi.ept" "-flatten")
ADD_TEST(test_option_flatten_format "scripts/test_option" "good/format.ept" "-flatten")
ADD_TEST(test_option_flatten_grosauto_clock "scripts/test_option" "good/grosauto_clock.ept" "-flatten")
ADD_TEST(test_option_flatten_hierarchie "scripts/test_option" "good/hierarchie.ept" "-flatten")
ADD_TEST(test_option_flatten_itfusion "scripts/test_option" "good/itfusion.ept" "-flatten")
ADD_TEST(test_option_flatten_linear_automata "scripts/test_option" "good/linear_automata.ept" "-flatten")
ADD_TEST(test_option_flatten_linear "scripts/test_option" "good/linear.ept" "-flatten")
ADD_TEST(test_option_flatten_linear_init "scripts/test_option" "good/linear_init.ept" "-flatten")
ADD_TEST(test_option_flatten_linear_split "scripts/test_option" "good/linear_split.ept" "-flatten")
ADD_TEST(test_option_flatten_linear_vars "scripts/test_option" "good/linear_vars.ept" "-flatten")
ADD_TEST(test_option_flatten_mapnot "scripts/test_option" "good/mapnot.ept" "-flatten")
ADD_TEST(test_option_flatten_memalloc_clocks "scripts/test_option" "good/memalloc_clocks.ept" "-flatten")
ADD_TEST(test_option_flatten_memalloc_record "scripts/test_option" "good/memalloc_record.ept" "-flatten")
ADD_TEST(test_option_flatten_memalloc_simple "scripts/test_option" "good/memalloc_simple.ept" "-flatten")
ADD_TEST(test_option_flatten_minus_pre "scripts/test_option" "good/minus_pre.ept" "-flatten")
ADD_TEST(test_option_flatten_name_clash "scripts/test_option" "good/name_clash.ept" "-flatten")
ADD_TEST(test_option_flatten_norm "scripts/test_option" "good/norm.ept" "-flatten")
ADD_TEST(test_option_flatten_or_keep "scripts/test_option" "good/or_keep.ept" "-flatten")
ADD_TEST(test_option_flatten_parametrize "scripts/test_option" "good/parametrize.ept" "-flatten")
ADD_TEST(test_option_flatten_pip "scripts/test_option" "good/pip.ept" "-flatten")
ADD_TEST(test_option_flatten_pip_slice "scripts/test_option" "good/pip_slice.ept" "-flatten")
ADD_TEST(test_option_flatten_pre_tuple "scripts/test_option" "good/pre_tuple.ept" "-flatten")
ADD_TEST(test_option_flatten_quasi "scripts/test_option" "good/quasi.ept" "-flatten")
ADD_TEST(test_option_flatten_reinit "scripts/test_option" "good/reinit.ept" "-flatten")
ADD_TEST(test_option_flatten_sampling_stateful_output2 "scripts/test_option" "good/sampling_stateful_output2.ept" "-flatten")
ADD_TEST(test_option_flatten_sampling_stateful_output "scripts/test_option" "good/sampling_stateful_output.ept" "-flatten")
ADD_TEST(test_option_flatten_side_effet "scripts/test_option" "good/side_effet.ept" "-flatten")
ADD_TEST(test_option_flatten_statics1 "scripts/test_option" "good/statics1.ept" "-flatten")
ADD_TEST(test_option_flatten_statics2 "scripts/test_option" "good/statics2.ept" "-flatten")
ADD_TEST(test_option_flatten_statics "scripts/test_option" "good/statics.ept" "-flatten")
ADD_TEST(test_option_flatten_t10 "scripts/test_option" "good/t10.ept" "-flatten")
ADD_TEST(test_option_flatten_t11 "scripts/test_option" "good/t11.ept" "-flatten")
ADD_TEST(test_option_flatten_t12 "scripts/test_option" "good/t12.ept" "-flatten")
ADD_TEST(test_option_flatten_t13 "scripts/test_option" "good/t13.ept" "-flatten")
ADD_TEST(test_option_flatten_t14 "scripts/test_option" "good/t14.ept" "-flatten")
ADD_TEST(test_option_flatten_t15 "scripts/test_option" "good/t15.ept" "-flatten")
ADD_TEST(test_option_flatten_t16 "scripts/test_option" "good/t16.ept" "-flatten")
ADD_TEST(test_option_flatten_t17 "scripts/test_option" "good/t17.ept" "-flatten")
ADD_TEST(test_option_flatten_t18 "scripts/test_option" "good/t18.ept" "-flatten")
ADD_TEST(test_option_flatten_t19 "scripts/test_option" "good/t19.ept" "-flatten")
ADD_TEST(test_option_flatten_t1 "scripts/test_option" "good/t1.ept" "-flatten")
ADD_TEST(test_option_flatten_t2 "scripts/test_option" "good/t2.ept" "-flatten")
ADD_TEST(test_option_flatten_t2open "scripts/test_option" "good/t2open.ept" "-flatten")
ADD_TEST(test_option_flatten_t3 "scripts/test_option" "good/t3.ept" "-flatten")
ADD_TEST(test_option_flatten_t4 "scripts/test_option" "good/t4.ept" "-flatten")
ADD_TEST(test_option_flatten_t5 "scripts/test_option" "good/t5.ept" "-flatten")
ADD_TEST(test_option_flatten_t6 "scripts/test_option" "good/t6.ept" "-flatten")
ADD_TEST(test_option_flatten_t7 "scripts/test_option" "good/t7.ept" "-flatten")
ADD_TEST(test_option_flatten_t8 "scripts/test_option" "good/t8.ept" "-flatten")
ADD_TEST(test_option_flatten_t9 "scripts/test_option" "good/t9.ept" "-flatten")
ADD_TEST(test_option_flatten_t "scripts/test_option" "good/t.ept" "-flatten")
ADD_TEST(test_option_flatten_test "scripts/test_option" "good/test.ept" "-flatten")
ADD_TEST(test_option_flatten_threestates "scripts/test_option" "good/threestates.ept" "-flatten")
ADD_TEST(test_option_flatten_tt "scripts/test_option" "good/tt.ept" "-flatten")
ADD_TEST(test_option_flatten_tttt "scripts/test_option" "good/tttt.ept" "-flatten")
ADD_TEST(test_option_flatten_tuple_args "scripts/test_option" "good/tuple_args.ept" "-flatten")
ADD_TEST(test_option_flatten_type_alias "scripts/test_option" "good/type_alias.ept" "-flatten")
ADD_TEST(test_option_flatten_updown "scripts/test_option" "good/updown.ept" "-flatten")
ADD_TEST(test_option_flatten_when_merge1 "scripts/test_option" "good/when_merge1.ept" "-flatten")
ADD_TEST(test_option_flatten_xor "scripts/test_option" "good/xor.ept" "-flatten")
ADD_TEST(test_option_itfusion_ais "scripts/test_option" "good/ais.ept" "-itfusion")
ADD_TEST(test_option_itfusion_alloc "scripts/test_option" "good/alloc.ept" "-itfusion")
ADD_TEST(test_option_itfusion_array1 "scripts/test_option" "good/array1.ept" "-itfusion")
ADD_TEST(test_option_itfusion_array2 "scripts/test_option" "good/array2.ept" "-itfusion")
ADD_TEST(test_option_itfusion_array_fill "scripts/test_option" "good/array_fill.ept" "-itfusion")
ADD_TEST(test_option_itfusion_array_iterators2 "scripts/test_option" "good/array_iterators2.ept" "-itfusion")
ADD_TEST(test_option_itfusion_array_iterators "scripts/test_option" "good/array_iterators.ept" "-itfusion")
ADD_TEST(test_option_itfusion_array_power "scripts/test_option" "good/array_power.ept" "-itfusion")
ADD_TEST(test_option_itfusion_auto_clock "scripts/test_option" "good/auto_clock.ept" "-itfusion")
ADD_TEST(test_option_itfusion_auto "scripts/test_option" "good/auto.ept" "-itfusion")
ADD_TEST(test_option_itfusion_autohiera2 "scripts/test_option" "good/autohiera2.ept" "-itfusion")
ADD_TEST(test_option_itfusion_autohiera3 "scripts/test_option" "good/autohiera3.ept" "-itfusion")
ADD_TEST(test_option_itfusion_autohiera "scripts/test_option" "good/autohiera.ept" "-itfusion")
ADD_TEST(test_option_itfusion_bad_updown "scripts/test_option" "good/bad_updown.ept" "-itfusion")
ADD_TEST(test_option_itfusion_ce "scripts/test_option" "good/ce.ept" "-itfusion")
ADD_TEST(test_option_itfusion_ckannot "scripts/test_option" "good/ckannot.ept" "-itfusion")
ADD_TEST(test_option_itfusion_clock_causality "scripts/test_option" "good/clock_causality.ept" "-itfusion")
ADD_TEST(test_option_itfusion_clocks "scripts/test_option" "good/clocks.ept" "-itfusion")
ADD_TEST(test_option_itfusion_const_record "scripts/test_option" "good/const_record.ept" "-itfusion")
ADD_TEST(test_option_itfusion_const_scope "scripts/test_option" "good/const_scope.ept" "-itfusion")
ADD_TEST(test_option_itfusion_contract_automaton "scripts/test_option" "good/contract_automaton.ept" "-itfusion")
ADD_TEST(test_option_itfusion_contract "scripts/test_option" "good/contract.ept" "-itfusion")
ADD_TEST(test_option_itfusion_convolutions "scripts/test_option" "good/convolutions.ept" "-itfusion")
ADD_TEST(test_option_itfusion_counter "scripts/test_option" "good/counter.ept" "-itfusion")
ADD_TEST(test_option_itfusion_current "scripts/test_option" "good/current.ept" "-itfusion")
ADD_TEST(test_option_itfusion_downscale "scripts/test_option" "good/downscale.ept" "-itfusion")
ADD_TEST(test_option_itfusion_fbyfby2 "scripts/test_option" "good/fbyfby2.ept" "-itfusion")
ADD_TEST(test_option_itfusion_foldi_arrays "scripts/test_option" "good/foldi_arrays.ept" "-itfusion")
ADD_TEST(test_option_itfusion_foldi "scripts/test_option" "good/foldi.ept" "-itfusion")
ADD_TEST(test_option_itfusion_format "scripts/test_option" "good/format.ept" "-itfusion")
ADD_TEST(test_option_itfusion_grosauto_clock "scripts/test_option" "good/grosauto_clock.ept" "-itfusion")
ADD_TEST(test_option_itfusion_hierarchie "scripts/test_option" "good/hierarchie.ept" "-itfusion")
ADD_TEST(test_option_itfusion_itfusion "scripts/test_option" "good/itfusion.ept" "-itfusion")
ADD_TEST(test_option_itfusion_linear_automata "scripts/test_option" "good/linear_automata.ept" "-itfusion")
ADD_TEST(test_option_itfusion_linear "scripts/test_option" "good/linear.ept" "-itfusion")
ADD_TEST(test_option_itfusion_linear_init "scripts/test_option" "good/linear_init.ept" "-itfusion")
ADD_TEST(test_option_itfusion_linear_split "scripts/test_option" "good/linear_split.ept" "-itfusion")
ADD_TEST(test_option_itfusion_linear_vars "scripts/test_option" "good/linear_vars.ept" "-itfusion")
ADD_TEST(test_option_itfusion_mapnot "scripts/test_option" "good/mapnot.ept" "-itfusion")
ADD_TEST(test_option_itfusion_memalloc_clocks "scripts/test_option" "good/memalloc_clocks.ept" "-itfusion")
ADD_TEST(test_option_itfusion_memalloc_record "scripts/test_option" "good/memalloc_record.ept" "-itfusion")
ADD_TEST(test_option_itfusion_memalloc_simple "scripts/test_option" "good/memalloc_simple.ept" "-itfusion")
ADD_TEST(test_option_itfusion_minus_pre "scripts/test_option" "good/minus_pre.ept" "-itfusion")
ADD_TEST(test_option_itfusion_name_clash "scripts/test_option" "good/name_clash.ept" "-itfusion")
ADD_TEST(test_option_itfusion_norm "scripts/test_option" "good/norm.ept" "-itfusion")
ADD_TEST(test_option_itfusion_or_keep "scripts/test_option" "good/or_keep.ept" "-itfusion")
ADD_TEST(test_option_itfusion_parametrize "scripts/test_option" "good/parametrize.ept" "-itfusion")
ADD_TEST(test_option_itfusion_pip "scripts/test_option" "good/pip.ept" "-itfusion")
ADD_TEST(test_option_itfusion_pip_slice "scripts/test_option" "good/pip_slice.ept" "-itfusion")
ADD_TEST(test_option_itfusion_pre_tuple "scripts/test_option" "good/pre_tuple.ept" "-itfusion")
ADD_TEST(test_option_itfusion_quasi "scripts/test_option" "good/quasi.ept" "-itfusion")
ADD_TEST(test_option_itfusion_reinit "scripts/test_option" "good/reinit.ept" "-itfusion")
ADD_TEST(test_option_itfusion_sampling_stateful_output2 "scripts/test_option" "good/sampling_stateful_output2.ept" "-itfusion")
ADD_TEST(test_option_itfusion_sampling_stateful_output "scripts/test_option" "good/sampling_stateful_output.ept" "-itfusion")
ADD_TEST(test_option_itfusion_side_effet "scripts/test_option" "good/side_effet.ept" "-itfusion")
ADD_TEST(test_option_itfusion_statics1 "scripts/test_option" "good/statics1.ept" "-itfusion")
ADD_TEST(test_option_itfusion_statics2 "scripts/test_option" "good/statics2.ept" "-itfusion")
ADD_TEST(test_option_itfusion_statics "scripts/test_option" "good/statics.ept" "-itfusion")
ADD_TEST(test_option_itfusion_t10 "scripts/test_option" "good/t10.ept" "-itfusion")
ADD_TEST(test_option_itfusion_t11 "scripts/test_option" "good/t11.ept" "-itfusion")
ADD_TEST(test_option_itfusion_t12 "scripts/test_option" "good/t12.ept" "-itfusion")
ADD_TEST(test_option_itfusion_t13 "scripts/test_option" "good/t13.ept" "-itfusion")
ADD_TEST(test_option_itfusion_t14 "scripts/test_option" "good/t14.ept" "-itfusion")
ADD_TEST(test_option_itfusion_t15 "scripts/test_option" "good/t15.ept" "-itfusion")
ADD_TEST(test_option_itfusion_t16 "scripts/test_option" "good/t16.ept" "-itfusion")
ADD_TEST(test_option_itfusion_t17 "scripts/test_option" "good/t17.ept" "-itfusion")
ADD_TEST(test_option_itfusion_t18 "scripts/test_option" "good/t18.ept" "-itfusion")
ADD_TEST(test_option_itfusion_t19 "scripts/test_option" "good/t19.ept" "-itfusion")
ADD_TEST(test_option_itfusion_t1 "scripts/test_option" "good/t1.ept" "-itfusion")
ADD_TEST(test_option_itfusion_t2 "scripts/test_option" "good/t2.ept" "-itfusion")
ADD_TEST(test_option_itfusion_t2open "scripts/test_option" "good/t2open.ept" "-itfusion")
ADD_TEST(test_option_itfusion_t3 "scripts/test_option" "good/t3.ept" "-itfusion")
ADD_TEST(test_option_itfusion_t4 "scripts/test_option" "good/t4.ept" "-itfusion")
ADD_TEST(test_option_itfusion_t5 "scripts/test_option" "good/t5.ept" "-itfusion")
ADD_TEST(test_option_itfusion_t6 "scripts/test_option" "good/t6.ept" "-itfusion")
ADD_TEST(test_option_itfusion_t7 "scripts/test_option" "good/t7.ept" "-itfusion")
ADD_TEST(test_option_itfusion_t8 "scripts/test_option" "good/t8.ept" "-itfusion")
ADD_TEST(test_option_itfusion_t9 "scripts/test_option" "good/t9.ept" "-itfusion")
ADD_TEST(test_option_itfusion_t "scripts/test_option" "good/t.ept" "-itfusion")
ADD_TEST(test_option_itfusion_test "scripts/test_option" "good/test.ept" "-itfusion")
ADD_TEST(test_option_itfusion_threestates "scripts/test_option" "good/threestates.ept" "-itfusion")
ADD_TEST(test_option_itfusion_tt "scripts/test_option" "good/tt.ept" "-itfusion")
ADD_TEST(test_option_itfusion_tttt "scripts/test_option" "good/tttt.ept" "-itfusion")
ADD_TEST(test_option_itfusion_tuple_args "scripts/test_option" "good/tuple_args.ept" "-itfusion")
ADD_TEST(test_option_itfusion_type_alias "scripts/test_option" "good/type_alias.ept" "-itfusion")
ADD_TEST(test_option_itfusion_updown "scripts/test_option" "good/updown.ept" "-itfusion")
ADD_TEST(test_option_itfusion_when_merge1 "scripts/test_option" "good/when_merge1.ept" "-itfusion")
ADD_TEST(test_option_itfusion_xor "scripts/test_option" "good/xor.ept" "-itfusion")
ADD_TEST(test_option_memalloc_ais "scripts/test_option" "good/ais.ept" "-memalloc")
ADD_TEST(test_option_memalloc_alloc "scripts/test_option" "good/alloc.ept" "-memalloc")
ADD_TEST(test_option_memalloc_array1 "scripts/test_option" "good/array1.ept" "-memalloc")
ADD_TEST(test_option_memalloc_array2 "scripts/test_option" "good/array2.ept" "-memalloc")
ADD_TEST(test_option_memalloc_array_fill "scripts/test_option" "good/array_fill.ept" "-memalloc")
ADD_TEST(test_option_memalloc_array_iterators2 "scripts/test_option" "good/array_iterators2.ept" "-memalloc")
ADD_TEST(test_option_memalloc_array_iterators "scripts/test_option" "good/array_iterators.ept" "-memalloc")
ADD_TEST(test_option_memalloc_array_power "scripts/test_option" "good/array_power.ept" "-memalloc")
ADD_TEST(test_option_memalloc_auto_clock "scripts/test_option" "good/auto_clock.ept" "-memalloc")
ADD_TEST(test_option_memalloc_auto "scripts/test_option" "good/auto.ept" "-memalloc")
ADD_TEST(test_option_memalloc_autohiera2 "scripts/test_option" "good/autohiera2.ept" "-memalloc")
ADD_TEST(test_option_memalloc_autohiera3 "scripts/test_option" "good/autohiera3.ept" "-memalloc")
ADD_TEST(test_option_memalloc_autohiera "scripts/test_option" "good/autohiera.ept" "-memalloc")
ADD_TEST(test_option_memalloc_bad_updown "scripts/test_option" "good/bad_updown.ept" "-memalloc")
ADD_TEST(test_option_memalloc_ce "scripts/test_option" "good/ce.ept" "-memalloc")
ADD_TEST(test_option_memalloc_ckannot "scripts/test_option" "good/ckannot.ept" "-memalloc")
ADD_TEST(test_option_memalloc_clock_causality "scripts/test_option" "good/clock_causality.ept" "-memalloc")
ADD_TEST(test_option_memalloc_clocks "scripts/test_option" "good/clocks.ept" "-memalloc")
ADD_TEST(test_option_memalloc_const_record "scripts/test_option" "good/const_record.ept" "-memalloc")
ADD_TEST(test_option_memalloc_const_scope "scripts/test_option" "good/const_scope.ept" "-memalloc")
ADD_TEST(test_option_memalloc_contract_automaton "scripts/test_option" "good/contract_automaton.ept" "-memalloc")
ADD_TEST(test_option_memalloc_contract "scripts/test_option" "good/contract.ept" "-memalloc")
ADD_TEST(test_option_memalloc_convolutions "scripts/test_option" "good/convolutions.ept" "-memalloc")
ADD_TEST(test_option_memalloc_counter "scripts/test_option" "good/counter.ept" "-memalloc")
ADD_TEST(test_option_memalloc_current "scripts/test_option" "good/current.ept" "-memalloc")
ADD_TEST(test_option_memalloc_downscale "scripts/test_option" "good/downscale.ept" "-memalloc")
ADD_TEST(test_option_memalloc_fbyfby2 "scripts/test_option" "good/fbyfby2.ept" "-memalloc")
ADD_TEST(test_option_memalloc_foldi_arrays "scripts/test_option" "good/foldi_arrays.ept" "-memalloc")
ADD_TEST(test_option_memalloc_foldi "scripts/test_option" "good/foldi.ept" "-memalloc")
ADD_TEST(test_option_memalloc_format "scripts/test_option" "good/format.ept" "-memalloc")
ADD_TEST(test_option_memalloc_grosauto_clock "scripts/test_option" "good/grosauto_clock.ept" "-memalloc")
ADD_TEST(test_option_memalloc_hierarchie "scripts/test_option" "good/hierarchie.ept" "-memalloc")
ADD_TEST(test_option_memalloc_itfusion "scripts/test_option" "good/itfusion.ept" "-memalloc")
ADD_TEST(test_option_memalloc_linear_automata "scripts/test_option" "good/linear_automata.ept" "-memalloc")
ADD_TEST(test_option_memalloc_linear "scripts/test_option" "good/linear.ept" "-memalloc")
ADD_TEST(test_option_memalloc_linear_init "scripts/test_option" "good/linear_init.ept" "-memalloc")
ADD_TEST(test_option_memalloc_linear_split "scripts/test_option" "good/linear_split.ept" "-memalloc")
ADD_TEST(test_option_memalloc_linear_vars "scripts/test_option" "good/linear_vars.ept" "-memalloc")
ADD_TEST(test_option_memalloc_mapnot "scripts/test_option" "good/mapnot.ept" "-memalloc")
ADD_TEST(test_option_memalloc_memalloc_clocks "scripts/test_option" "good/memalloc_clocks.ept" "-memalloc")
ADD_TEST(test_option_memalloc_memalloc_record "scripts/test_option" "good/memalloc_record.ept" "-memalloc")
ADD_TEST(test_option_memalloc_memalloc_simple "scripts/test_option" "good/memalloc_simple.ept" "-memalloc")
ADD_TEST(test_option_memalloc_minus_pre "scripts/test_option" "good/minus_pre.ept" "-memalloc")
ADD_TEST(test_option_memalloc_name_clash "scripts/test_option" "good/name_clash.ept" "-memalloc")
ADD_TEST(test_option_memalloc_norm "scripts/test_option" "good/norm.ept" "-memalloc")
ADD_TEST(test_option_memalloc_or_keep "scripts/test_option" "good/or_keep.ept" "-memalloc")
ADD_TEST(test_option_memalloc_parametrize "scripts/test_option" "good/parametrize.ept" "-memalloc")
ADD_TEST(test_option_memalloc_pip "scripts/test_option" "good/pip.ept" "-memalloc")
ADD_TEST(test_option_memalloc_pip_slice "scripts/test_option" "good/pip_slice.ept" "-memalloc")
ADD_TEST(test_option_memalloc_pre_tuple "scripts/test_option" "good/pre_tuple.ept" "-memalloc")
ADD_TEST(test_option_memalloc_quasi "scripts/test_option" "good/quasi.ept" "-memalloc")
ADD_TEST(test_option_memalloc_reinit "scripts/test_option" "good/reinit.ept" "-memalloc")
ADD_TEST(test_option_memalloc_sampling_stateful_output2 "scripts/test_option" "good/sampling_stateful_output2.ept" "-memalloc")
ADD_TEST(test_option_memalloc_sampling_stateful_output "scripts/test_option" "good/sampling_stateful_output.ept" "-memalloc")
ADD_TEST(test_option_memalloc_side_effet "scripts/test_option" "good/side_effet.ept" "-memalloc")
ADD_TEST(test_option_memalloc_statics1 "scripts/test_option" "good/statics1.ept" "-memalloc")
ADD_TEST(test_option_memalloc_statics2 "scripts/test_option" "good/statics2.ept" "-memalloc")
ADD_TEST(test_option_memalloc_statics "scripts/test_option" "good/statics.ept" "-memalloc")
ADD_TEST(test_option_memalloc_t10 "scripts/test_option" "good/t10.ept" "-memalloc")
ADD_TEST(test_option_memalloc_t11 "scripts/test_option" "good/t11.ept" "-memalloc")
ADD_TEST(test_option_memalloc_t12 "scripts/test_option" "good/t12.ept" "-memalloc")
ADD_TEST(test_option_memalloc_t13 "scripts/test_option" "good/t13.ept" "-memalloc")
ADD_TEST(test_option_memalloc_t14 "scripts/test_option" "good/t14.ept" "-memalloc")
ADD_TEST(test_option_memalloc_t15 "scripts/test_option" "good/t15.ept" "-memalloc")
ADD_TEST(test_option_memalloc_t16 "scripts/test_option" "good/t16.ept" "-memalloc")
ADD_TEST(test_option_memalloc_t17 "scripts/test_option" "good/t17.ept" "-memalloc")
ADD_TEST(test_option_memalloc_t18 "scripts/test_option" "good/t18.ept" "-memalloc")
ADD_TEST(test_option_memalloc_t19 "scripts/test_option" "good/t19.ept" "-memalloc")
ADD_TEST(test_option_memalloc_t1 "scripts/test_option" "good/t1.ept" "-memalloc")
ADD_TEST(test_option_memalloc_t2 "scripts/test_option" "good/t2.ept" "-memalloc")
ADD_TEST(test_option_memalloc_t2open "scripts/test_option" "good/t2open.ept" "-memalloc")
ADD_TEST(test_option_memalloc_t3 "scripts/test_option" "good/t3.ept" "-memalloc")
ADD_TEST(test_option_memalloc_t4 "scripts/test_option" "good/t4.ept" "-memalloc")
ADD_TEST(test_option_memalloc_t5 "scripts/test_option" "good/t5.ept" "-memalloc")
ADD_TEST(test_option_memalloc_t6 "scripts/test_option" "good/t6.ept" "-memalloc")
ADD_TEST(test_option_memalloc_t7 "scripts/test_option" "good/t7.ept" "-memalloc")
ADD_TEST(test_option_memalloc_t8 "scripts/test_option" "good/t8.ept" "-memalloc")
ADD_TEST(test_option_memalloc_t9 "scripts/test_option" "good/t9.ept" "-memalloc")
ADD_TEST(test_option_memalloc_t "scripts/test_option" "good/t.ept" "-memalloc")
ADD_TEST(test_option_memalloc_test "scripts/test_option" "good/test.ept" "-memalloc")
ADD_TEST(test_option_memalloc_threestates "scripts/test_option" "good/threestates.ept" "-memalloc")
ADD_TEST(test_option_memalloc_tt "scripts/test_option" "good/tt.ept" "-memalloc")
ADD_TEST(test_option_memalloc_tttt "scripts/test_option" "good/tttt.ept" "-memalloc")
ADD_TEST(test_option_memalloc_tuple_args "scripts/test_option" "good/tuple_args.ept" "-memalloc")
ADD_TEST(test_option_memalloc_type_alias "scripts/test_option" "good/type_alias.ept" "-memalloc")
ADD_TEST(test_option_memalloc_updown "scripts/test_option" "good/updown.ept" "-memalloc")
ADD_TEST(test_option_memalloc_when_merge1 "scripts/test_option" "good/when_merge1.ept" "-memalloc")
ADD_TEST(test_option_memalloc_xor "scripts/test_option" "good/xor.ept" "-memalloc")
ADD_TEST(test_option_unroll_ais "scripts/test_option" "good/ais.ept" "-unroll")
ADD_TEST(test_option_unroll_alloc "scripts/test_option" "good/alloc.ept" "-unroll")
ADD_TEST(test_option_unroll_array1 "scripts/test_option" "good/array1.ept" "-unroll")
ADD_TEST(test_option_unroll_array2 "scripts/test_option" "good/array2.ept" "-unroll")
ADD_TEST(test_option_unroll_array_fill "scripts/test_option" "good/array_fill.ept" "-unroll")
ADD_TEST(test_option_unroll_array_iterators2 "scripts/test_option" "good/array_iterators2.ept" "-unroll")
ADD_TEST(test_option_unroll_array_iterators "scripts/test_option" "good/array_iterators.ept" "-unroll")
ADD_TEST(test_option_unroll_array_power "scripts/test_option" "good/array_power.ept" "-unroll")
ADD_TEST(test_option_unroll_auto_clock "scripts/test_option" "good/auto_clock.ept" "-unroll")
ADD_TEST(test_option_unroll_auto "scripts/test_option" "good/auto.ept" "-unroll")
ADD_TEST(test_option_unroll_autohiera2 "scripts/test_option" "good/autohiera2.ept" "-unroll")
ADD_TEST(test_option_unroll_autohiera3 "scripts/test_option" "good/autohiera3.ept" "-unroll")
ADD_TEST(test_option_unroll_autohiera "scripts/test_option" "good/autohiera.ept" "-unroll")
ADD_TEST(test_option_unroll_bad_updown "scripts/test_option" "good/bad_updown.ept" "-unroll")
ADD_TEST(test_option_unroll_ce "scripts/test_option" "good/ce.ept" "-unroll")
ADD_TEST(test_option_unroll_ckannot "scripts/test_option" "good/ckannot.ept" "-unroll")
ADD_TEST(test_option_unroll_clock_causality "scripts/test_option" "good/clock_causality.ept" "-unroll")
ADD_TEST(test_option_unroll_clocks "scripts/test_option" "good/clocks.ept" "-unroll")
ADD_TEST(test_option_unroll_const_record "scripts/test_option" "good/const_record.ept" "-unroll")
ADD_TEST(test_option_unroll_const_scope "scripts/test_option" "good/const_scope.ept" "-unroll")
ADD_TEST(test_option_unroll_contract_automaton "scripts/test_option" "good/contract_automaton.ept" "-unroll")
ADD_TEST(test_option_unroll_contract "scripts/test_option" "good/contract.ept" "-unroll")
ADD_TEST(test_option_unroll_convolutions "scripts/test_option" "good/convolutions.ept" "-unroll")
ADD_TEST(test_option_unroll_counter "scripts/test_option" "good/counter.ept" "-unroll")
ADD_TEST(test_option_unroll_current "scripts/test_option" "good/current.ept" "-unroll")
ADD_TEST(test_option_unroll_downscale "scripts/test_option" "good/downscale.ept" "-unroll")
ADD_TEST(test_option_unroll_fbyfby2 "scripts/test_option" "good/fbyfby2.ept" "-unroll")
ADD_TEST(test_option_unroll_foldi_arrays "scripts/test_option" "good/foldi_arrays.ept" "-unroll")
ADD_TEST(test_option_unroll_foldi "scripts/test_option" "good/foldi.ept" "-unroll")
ADD_TEST(test_option_unroll_format "scripts/test_option" "good/format.ept" "-unroll")
ADD_TEST(test_option_unroll_grosauto_clock "scripts/test_option" "good/grosauto_clock.ept" "-unroll")
ADD_TEST(test_option_unroll_hierarchie "scripts/test_option" "good/hierarchie.ept" "-unroll")
ADD_TEST(test_option_unroll_itfusion "scripts/test_option" "good/itfusion.ept" "-unroll")
ADD_TEST(test_option_unroll_linear_automata "scripts/test_option" "good/linear_automata.ept" "-unroll")
ADD_TEST(test_option_unroll_linear "scripts/test_option" "good/linear.ept" "-unroll")
ADD_TEST(test_option_unroll_linear_init "scripts/test_option" "good/linear_init.ept" "-unroll")
ADD_TEST(test_option_unroll_linear_split "scripts/test_option" "good/linear_split.ept" "-unroll")
ADD_TEST(test_option_unroll_linear_vars "scripts/test_option" "good/linear_vars.ept" "-unroll")
ADD_TEST(test_option_unroll_mapnot "scripts/test_option" "good/mapnot.ept" "-unroll")
ADD_TEST(test_option_unroll_memalloc_clocks "scripts/test_option" "good/memalloc_clocks.ept" "-unroll")
ADD_TEST(test_option_unroll_memalloc_record "scripts/test_option" "good/memalloc_record.ept" "-unroll")
ADD_TEST(test_option_unroll_memalloc_simple "scripts/test_option" "good/memalloc_simple.ept" "-unroll")
ADD_TEST(test_option_unroll_minus_pre "scripts/test_option" "good/minus_pre.ept" "-unroll")
ADD_TEST(test_option_unroll_name_clash "scripts/test_option" "good/name_clash.ept" "-unroll")
ADD_TEST(test_option_unroll_norm "scripts/test_option" "good/norm.ept" "-unroll")
ADD_TEST(test_option_unroll_or_keep "scripts/test_option" "good/or_keep.ept" "-unroll")
ADD_TEST(test_option_unroll_parametrize "scripts/test_option" "good/parametrize.ept" "-unroll")
ADD_TEST(test_option_unroll_pip "scripts/test_option" "good/pip.ept" "-unroll")
ADD_TEST(test_option_unroll_pip_slice "scripts/test_option" "good/pip_slice.ept" "-unroll")
ADD_TEST(test_option_unroll_pre_tuple "scripts/test_option" "good/pre_tuple.ept" "-unroll")
ADD_TEST(test_option_unroll_quasi "scripts/test_option" "good/quasi.ept" "-unroll")
ADD_TEST(test_option_unroll_reinit "scripts/test_option" "good/reinit.ept" "-unroll")
ADD_TEST(test_option_unroll_sampling_stateful_output2 "scripts/test_option" "good/sampling_stateful_output2.ept" "-unroll")
ADD_TEST(test_option_unroll_sampling_stateful_output "scripts/test_option" "good/sampling_stateful_output.ept" "-unroll")
ADD_TEST(test_option_unroll_side_effet "scripts/test_option" "good/side_effet.ept" "-unroll")
ADD_TEST(test_option_unroll_statics1 "scripts/test_option" "good/statics1.ept" "-unroll")
ADD_TEST(test_option_unroll_statics2 "scripts/test_option" "good/statics2.ept" "-unroll")
ADD_TEST(test_option_unroll_statics "scripts/test_option" "good/statics.ept" "-unroll")
ADD_TEST(test_option_unroll_t10 "scripts/test_option" "good/t10.ept" "-unroll")
ADD_TEST(test_option_unroll_t11 "scripts/test_option" "good/t11.ept" "-unroll")
ADD_TEST(test_option_unroll_t12 "scripts/test_option" "good/t12.ept" "-unroll")
ADD_TEST(test_option_unroll_t13 "scripts/test_option" "good/t13.ept" "-unroll")
ADD_TEST(test_option_unroll_t14 "scripts/test_option" "good/t14.ept" "-unroll")
ADD_TEST(test_option_unroll_t15 "scripts/test_option" "good/t15.ept" "-unroll")
ADD_TEST(test_option_unroll_t16 "scripts/test_option" "good/t16.ept" "-unroll")
ADD_TEST(test_option_unroll_t17 "scripts/test_option" "good/t17.ept" "-unroll")
ADD_TEST(test_option_unroll_t18 "scripts/test_option" "good/t18.ept" "-unroll")
ADD_TEST(test_option_unroll_t19 "scripts/test_option" "good/t19.ept" "-unroll")
ADD_TEST(test_option_unroll_t1 "scripts/test_option" "good/t1.ept" "-unroll")
ADD_TEST(test_option_unroll_t2 "scripts/test_option" "good/t2.ept" "-unroll")
ADD_TEST(test_option_unroll_t2open "scripts/test_option" "good/t2open.ept" "-unroll")
ADD_TEST(test_option_unroll_t3 "scripts/test_option" "good/t3.ept" "-unroll")
ADD_TEST(test_option_unroll_t4 "scripts/test_option" "good/t4.ept" "-unroll")
ADD_TEST(test_option_unroll_t5 "scripts/test_option" "good/t5.ept" "-unroll")
ADD_TEST(test_option_unroll_t6 "scripts/test_option" "good/t6.ept" "-unroll")
ADD_TEST(test_option_unroll_t7 "scripts/test_option" "good/t7.ept" "-unroll")
ADD_TEST(test_option_unroll_t8 "scripts/test_option" "good/t8.ept" "-unroll")
ADD_TEST(test_option_unroll_t9 "scripts/test_option" "good/t9.ept" "-unroll")
ADD_TEST(test_option_unroll_t "scripts/test_option" "good/t.ept" "-unroll")
ADD_TEST(test_option_unroll_test "scripts/test_option" "good/test.ept" "-unroll")
ADD_TEST(test_option_unroll_threestates "scripts/test_option" "good/threestates.ept" "-unroll")
ADD_TEST(test_option_unroll_tt "scripts/test_option" "good/tt.ept" "-unroll")
ADD_TEST(test_option_unroll_tttt "scripts/test_option" "good/tttt.ept" "-unroll")
ADD_TEST(test_option_unroll_tuple_args "scripts/test_option" "good/tuple_args.ept" "-unroll")
ADD_TEST(test_option_unroll_type_alias "scripts/test_option" "good/type_alias.ept" "-unroll")
ADD_TEST(test_option_unroll_updown "scripts/test_option" "good/updown.ept" "-unroll")
ADD_TEST(test_option_unroll_when_merge1 "scripts/test_option" "good/when_merge1.ept" "-unroll")
ADD_TEST(test_option_unroll_xor "scripts/test_option" "good/xor.ept" "-unroll")
ADD_TEST(test_option_O_ais "scripts/test_option" "good/ais.ept" "-O")
ADD_TEST(test_option_O_alloc "scripts/test_option" "good/alloc.ept" "-O")
ADD_TEST(test_option_O_array1 "scripts/test_option" "good/array1.ept" "-O")
ADD_TEST(test_option_O_array2 "scripts/test_option" "good/array2.ept" "-O")
ADD_TEST(test_option_O_array_fill "scripts/test_option" "good/array_fill.ept" "-O")
ADD_TEST(test_option_O_array_iterators2 "scripts/test_option" "good/array_iterators2.ept" "-O")
ADD_TEST(test_option_O_array_iterators "scripts/test_option" "good/array_iterators.ept" "-O")
ADD_TEST(test_option_O_array_power "scripts/test_option" "good/array_power.ept" "-O")
ADD_TEST(test_option_O_auto_clock "scripts/test_option" "good/auto_clock.ept" "-O")
ADD_TEST(test_option_O_auto "scripts/test_option" "good/auto.ept" "-O")
ADD_TEST(test_option_O_autohiera2 "scripts/test_option" "good/autohiera2.ept" "-O")
ADD_TEST(test_option_O_autohiera3 "scripts/test_option" "good/autohiera3.ept" "-O")
ADD_TEST(test_option_O_autohiera "scripts/test_option" "good/autohiera.ept" "-O")
ADD_TEST(test_option_O_bad_updown "scripts/test_option" "good/bad_updown.ept" "-O")
ADD_TEST(test_option_O_ce "scripts/test_option" "good/ce.ept" "-O")
ADD_TEST(test_option_O_ckannot "scripts/test_option" "good/ckannot.ept" "-O")
ADD_TEST(test_option_O_clock_causality "scripts/test_option" "good/clock_causality.ept" "-O")
ADD_TEST(test_option_O_clocks "scripts/test_option" "good/clocks.ept" "-O")
ADD_TEST(test_option_O_const_record "scripts/test_option" "good/const_record.ept" "-O")
ADD_TEST(test_option_O_const_scope "scripts/test_option" "good/const_scope.ept" "-O")
ADD_TEST(test_option_O_contract_automaton "scripts/test_option" "good/contract_automaton.ept" "-O")
ADD_TEST(test_option_O_contract "scripts/test_option" "good/contract.ept" "-O")
ADD_TEST(test_option_O_convolutions "scripts/test_option" "good/convolutions.ept" "-O")
ADD_TEST(test_option_O_counter "scripts/test_option" "good/counter.ept" "-O")
ADD_TEST(test_option_O_current "scripts/test_option" "good/current.ept" "-O")
ADD_TEST(test_option_O_downscale "scripts/test_option" "good/downscale.ept" "-O")
ADD_TEST(test_option_O_fbyfby2 "scripts/test_option" "good/fbyfby2.ept" "-O")
ADD_TEST(test_option_O_foldi_arrays "scripts/test_option" "good/foldi_arrays.ept" "-O")
ADD_TEST(test_option_O_foldi "scripts/test_option" "good/foldi.ept" "-O")
ADD_TEST(test_option_O_format "scripts/test_option" "good/format.ept" "-O")
ADD_TEST(test_option_O_grosauto_clock "scripts/test_option" "good/grosauto_clock.ept" "-O")
ADD_TEST(test_option_O_hierarchie "scripts/test_option" "good/hierarchie.ept" "-O")
ADD_TEST(test_option_O_itfusion "scripts/test_option" "good/itfusion.ept" "-O")
ADD_TEST(test_option_O_linear_automata "scripts/test_option" "good/linear_automata.ept" "-O")
ADD_TEST(test_option_O_linear "scripts/test_option" "good/linear.ept" "-O")
ADD_TEST(test_option_O_linear_init "scripts/test_option" "good/linear_init.ept" "-O")
ADD_TEST(test_option_O_linear_split "scripts/test_option" "good/linear_split.ept" "-O")
ADD_TEST(test_option_O_linear_vars "scripts/test_option" "good/linear_vars.ept" "-O")
ADD_TEST(test_option_O_mapnot "scripts/test_option" "good/mapnot.ept" "-O")
ADD_TEST(test_option_O_memalloc_clocks "scripts/test_option" "good/memalloc_clocks.ept" "-O")
ADD_TEST(test_option_O_memalloc_record "scripts/test_option" "good/memalloc_record.ept" "-O")
ADD_TEST(test_option_O_memalloc_simple "scripts/test_option" "good/memalloc_simple.ept" "-O")
ADD_TEST(test_option_O_minus_pre "scripts/test_option" "good/minus_pre.ept" "-O")
ADD_TEST(test_option_O_name_clash "scripts/test_option" "good/name_clash.ept" "-O")
ADD_TEST(test_option_O_norm "scripts/test_option" "good/norm.ept" "-O")
ADD_TEST(test_option_O_or_keep "scripts/test_option" "good/or_keep.ept" "-O")
ADD_TEST(test_option_O_parametrize "scripts/test_option" "good/parametrize.ept" "-O")
ADD_TEST(test_option_O_pip "scripts/test_option" "good/pip.ept" "-O")
ADD_TEST(test_option_O_pip_slice "scripts/test_option" "good/pip_slice.ept" "-O")
ADD_TEST(test_option_O_pre_tuple "scripts/test_option" "good/pre_tuple.ept" "-O")
ADD_TEST(test_option_O_quasi "scripts/test_option" "good/quasi.ept" "-O")
ADD_TEST(test_option_O_reinit "scripts/test_option" "good/reinit.ept" "-O")
ADD_TEST(test_option_O_sampling_stateful_output2 "scripts/test_option" "good/sampling_stateful_output2.ept" "-O")
ADD_TEST(test_option_O_sampling_stateful_output "scripts/test_option" "good/sampling_stateful_output.ept" "-O")
ADD_TEST(test_option_O_side_effet "scripts/test_option" "good/side_effet.ept" "-O")
ADD_TEST(test_option_O_statics1 "scripts/test_option" "good/statics1.ept" "-O")
ADD_TEST(test_option_O_statics2 "scripts/test_option" "good/statics2.ept" "-O")
ADD_TEST(test_option_O_statics "scripts/test_option" "good/statics.ept" "-O")
ADD_TEST(test_option_O_t10 "scripts/test_option" "good/t10.ept" "-O")
ADD_TEST(test_option_O_t11 "scripts/test_option" "good/t11.ept" "-O")
ADD_TEST(test_option_O_t12 "scripts/test_option" "good/t12.ept" "-O")
ADD_TEST(test_option_O_t13 "scripts/test_option" "good/t13.ept" "-O")
ADD_TEST(test_option_O_t14 "scripts/test_option" "good/t14.ept" "-O")
ADD_TEST(test_option_O_t15 "scripts/test_option" "good/t15.ept" "-O")
ADD_TEST(test_option_O_t16 "scripts/test_option" "good/t16.ept" "-O")
ADD_TEST(test_option_O_t17 "scripts/test_option" "good/t17.ept" "-O")
ADD_TEST(test_option_O_t18 "scripts/test_option" "good/t18.ept" "-O")
ADD_TEST(test_option_O_t19 "scripts/test_option" "good/t19.ept" "-O")
ADD_TEST(test_option_O_t1 "scripts/test_option" "good/t1.ept" "-O")
ADD_TEST(test_option_O_t2 "scripts/test_option" "good/t2.ept" "-O")
ADD_TEST(test_option_O_t2open "scripts/test_option" "good/t2open.ept" "-O")
ADD_TEST(test_option_O_t3 "scripts/test_option" "good/t3.ept" "-O")
ADD_TEST(test_option_O_t4 "scripts/test_option" "good/t4.ept" "-O")
ADD_TEST(test_option_O_t5 "scripts/test_option" "good/t5.ept" "-O")
ADD_TEST(test_option_O_t6 "scripts/test_option" "good/t6.ept" "-O")
ADD_TEST(test_option_O_t7 "scripts/test_option" "good/t7.ept" "-O")
ADD_TEST(test_option_O_t8 "scripts/test_option" "good/t8.ept" "-O")
ADD_TEST(test_option_O_t9 "scripts/test_option" "good/t9.ept" "-O")
ADD_TEST(test_option_O_t "scripts/test_option" "good/t.ept" "-O")
ADD_TEST(test_option_O_test "scripts/test_option" "good/test.ept" "-O")
ADD_TEST(test_option_O_threestates "scripts/test_option" "good/threestates.ept" "-O")
ADD_TEST(test_option_O_tt "scripts/test_option" "good/tt.ept" "-O")
ADD_TEST(test_option_O_tttt "scripts/test_option" "good/tttt.ept" "-O")
ADD_TEST(test_option_O_tuple_args "scripts/test_option" "good/tuple_args.ept" "-O")
ADD_TEST(test_option_O_type_alias "scripts/test_option" "good/type_alias.ept" "-O")
ADD_TEST(test_option_O_updown "scripts/test_option" "good/updown.ept" "-O")
ADD_TEST(test_option_O_when_merge1 "scripts/test_option" "good/when_merge1.ept" "-O")
ADD_TEST(test_option_O_xor "scripts/test_option" "good/xor.ept" "-O")
ADD_TEST(compile_javac_run_ais "scripts/compile_javac_run" "good/ais.ept")
ADD_TEST(compile_javac_run_alloc "scripts/compile_javac_run" "good/alloc.ept")
ADD_TEST(compile_javac_run_array1 "scripts/compile_javac_run" "good/array1.ept")
ADD_TEST(compile_javac_run_array2 "scripts/compile_javac_run" "good/array2.ept")
ADD_TEST(compile_javac_run_array_fill "scripts/compile_javac_run" "good/array_fill.ept")
ADD_TEST(compile_javac_run_array_iterators2 "scripts/compile_javac_run" "good/array_iterators2.ept")
ADD_TEST(compile_javac_run_array_iterators "scripts/compile_javac_run" "good/array_iterators.ept")
ADD_TEST(compile_javac_run_array_power "scripts/compile_javac_run" "good/array_power.ept")
ADD_TEST(compile_javac_run_auto_clock "scripts/compile_javac_run" "good/auto_clock.ept")
ADD_TEST(compile_javac_run_auto "scripts/compile_javac_run" "good/auto.ept")
ADD_TEST(compile_javac_run_autohiera2 "scripts/compile_javac_run" "good/autohiera2.ept")
ADD_TEST(compile_javac_run_autohiera3 "scripts/compile_javac_run" "good/autohiera3.ept")
ADD_TEST(compile_javac_run_autohiera "scripts/compile_javac_run" "good/autohiera.ept")
ADD_TEST(compile_javac_run_bad_updown "scripts/compile_javac_run" "good/bad_updown.ept")
ADD_TEST(compile_javac_run_ce "scripts/compile_javac_run" "good/ce.ept")
ADD_TEST(compile_javac_run_ckannot "scripts/compile_javac_run" "good/ckannot.ept")
ADD_TEST(compile_javac_run_clock_causality "scripts/compile_javac_run" "good/clock_causality.ept")
ADD_TEST(compile_javac_run_clocks "scripts/compile_javac_run" "good/clocks.ept")
ADD_TEST(compile_javac_run_const_record "scripts/compile_javac_run" "good/const_record.ept")
ADD_TEST(compile_javac_run_const_scope "scripts/compile_javac_run" "good/const_scope.ept")
ADD_TEST(compile_javac_run_contract_automaton "scripts/compile_javac_run" "good/contract_automaton.ept")
ADD_TEST(compile_javac_run_contract "scripts/compile_javac_run" "good/contract.ept")
ADD_TEST(compile_javac_run_convolutions "scripts/compile_javac_run" "good/convolutions.ept")
ADD_TEST(compile_javac_run_counter "scripts/compile_javac_run" "good/counter.ept")
ADD_TEST(compile_javac_run_current "scripts/compile_javac_run" "good/current.ept")
ADD_TEST(compile_javac_run_downscale "scripts/compile_javac_run" "good/downscale.ept")
ADD_TEST(compile_javac_run_fbyfby2 "scripts/compile_javac_run" "good/fbyfby2.ept")
ADD_TEST(compile_javac_run_foldi_arrays "scripts/compile_javac_run" "good/foldi_arrays.ept")
ADD_TEST(compile_javac_run_foldi "scripts/compile_javac_run" "good/foldi.ept")
ADD_TEST(compile_javac_run_format "scripts/compile_javac_run" "good/format.ept")
ADD_TEST(compile_javac_run_grosauto_clock "scripts/compile_javac_run" "good/grosauto_clock.ept")
ADD_TEST(compile_javac_run_hierarchie "scripts/compile_javac_run" "good/hierarchie.ept")
ADD_TEST(compile_javac_run_itfusion "scripts/compile_javac_run" "good/itfusion.ept")
ADD_TEST(compile_javac_run_linear_automata "scripts/compile_javac_run" "good/linear_automata.ept")
ADD_TEST(compile_javac_run_linear "scripts/compile_javac_run" "good/linear.ept")
ADD_TEST(compile_javac_run_linear_init "scripts/compile_javac_run" "good/linear_init.ept")
ADD_TEST(compile_javac_run_linear_split "scripts/compile_javac_run" "good/linear_split.ept")
ADD_TEST(compile_javac_run_linear_vars "scripts/compile_javac_run" "good/linear_vars.ept")
ADD_TEST(compile_javac_run_mapnot "scripts/compile_javac_run" "good/mapnot.ept")
ADD_TEST(compile_javac_run_memalloc_clocks "scripts/compile_javac_run" "good/memalloc_clocks.ept")
ADD_TEST(compile_javac_run_memalloc_record "scripts/compile_javac_run" "good/memalloc_record.ept")
ADD_TEST(compile_javac_run_memalloc_simple "scripts/compile_javac_run" "good/memalloc_simple.ept")
ADD_TEST(compile_javac_run_minus_pre "scripts/compile_javac_run" "good/minus_pre.ept")
ADD_TEST(compile_javac_run_name_clash "scripts/compile_javac_run" "good/name_clash.ept")
ADD_TEST(compile_javac_run_norm "scripts/compile_javac_run" "good/norm.ept")
ADD_TEST(compile_javac_run_or_keep "scripts/compile_javac_run" "good/or_keep.ept")
ADD_TEST(compile_javac_run_parametrize "scripts/compile_javac_run" "good/parametrize.ept")
ADD_TEST(compile_javac_run_pip "scripts/compile_javac_run" "good/pip.ept")
ADD_TEST(compile_javac_run_pip_slice "scripts/compile_javac_run" "good/pip_slice.ept")
ADD_TEST(compile_javac_run_pre_tuple "scripts/compile_javac_run" "good/pre_tuple.ept")
ADD_TEST(compile_javac_run_quasi "scripts/compile_javac_run" "good/quasi.ept")
ADD_TEST(compile_javac_run_reinit "scripts/compile_javac_run" "good/reinit.ept")
ADD_TEST(compile_javac_run_sampling_stateful_output2 "scripts/compile_javac_run" "good/sampling_stateful_output2.ept")
ADD_TEST(compile_javac_run_sampling_stateful_output "scripts/compile_javac_run" "good/sampling_stateful_output.ept")
ADD_TEST(compile_javac_run_side_effet "scripts/compile_javac_run" "good/side_effet.ept")
ADD_TEST(compile_javac_run_statics1 "scripts/compile_javac_run" "good/statics1.ept")
ADD_TEST(compile_javac_run_statics2 "scripts/compile_javac_run" "good/statics2.ept")
ADD_TEST(compile_javac_run_statics "scripts/compile_javac_run" "good/statics.ept")
ADD_TEST(compile_javac_run_t10 "scripts/compile_javac_run" "good/t10.ept")
ADD_TEST(compile_javac_run_t11 "scripts/compile_javac_run" "good/t11.ept")
ADD_TEST(compile_javac_run_t12 "scripts/compile_javac_run" "good/t12.ept")
ADD_TEST(compile_javac_run_t13 "scripts/compile_javac_run" "good/t13.ept")
ADD_TEST(compile_javac_run_t14 "scripts/compile_javac_run" "good/t14.ept")
ADD_TEST(compile_javac_run_t15 "scripts/compile_javac_run" "good/t15.ept")
ADD_TEST(compile_javac_run_t16 "scripts/compile_javac_run" "good/t16.ept")
ADD_TEST(compile_javac_run_t17 "scripts/compile_javac_run" "good/t17.ept")
ADD_TEST(compile_javac_run_t18 "scripts/compile_javac_run" "good/t18.ept")
ADD_TEST(compile_javac_run_t19 "scripts/compile_javac_run" "good/t19.ept")
ADD_TEST(compile_javac_run_t1 "scripts/compile_javac_run" "good/t1.ept")
ADD_TEST(compile_javac_run_t2 "scripts/compile_javac_run" "good/t2.ept")
ADD_TEST(compile_javac_run_t2open "scripts/compile_javac_run" "good/t2open.ept")
ADD_TEST(compile_javac_run_t3 "scripts/compile_javac_run" "good/t3.ept")
ADD_TEST(compile_javac_run_t4 "scripts/compile_javac_run" "good/t4.ept")
ADD_TEST(compile_javac_run_t5 "scripts/compile_javac_run" "good/t5.ept")
ADD_TEST(compile_javac_run_t6 "scripts/compile_javac_run" "good/t6.ept")
ADD_TEST(compile_javac_run_t7 "scripts/compile_javac_run" "good/t7.ept")
ADD_TEST(compile_javac_run_t8 "scripts/compile_javac_run" "good/t8.ept")
ADD_TEST(compile_javac_run_t9 "scripts/compile_javac_run" "good/t9.ept")
ADD_TEST(compile_javac_run_t "scripts/compile_javac_run" "good/t.ept")
ADD_TEST(compile_javac_run_test "scripts/compile_javac_run" "good/test.ept")
ADD_TEST(compile_javac_run_threestates "scripts/compile_javac_run" "good/threestates.ept")
ADD_TEST(compile_javac_run_tt "scripts/compile_javac_run" "good/tt.ept")
ADD_TEST(compile_javac_run_tttt "scripts/compile_javac_run" "good/tttt.ept")
ADD_TEST(compile_javac_run_tuple_args "scripts/compile_javac_run" "good/tuple_args.ept")
ADD_TEST(compile_javac_run_type_alias "scripts/compile_javac_run" "good/type_alias.ept")
ADD_TEST(compile_javac_run_updown "scripts/compile_javac_run" "good/updown.ept")
ADD_TEST(compile_javac_run_when_merge1 "scripts/compile_javac_run" "good/when_merge1.ept")
ADD_TEST(compile_javac_run_xor "scripts/compile_javac_run" "good/xor.ept")
ADD_TEST(compile_sdc_run_alloc "scripts/compile_sdc_run" "sdc/alloc.ept")
ADD_TEST(compile_sdc_run_contrenum "scripts/compile_sdc_run" "sdc/contrenum.ept")
ADD_TEST(compile_sdc_run_lnum_simple "scripts/compile_sdc_run" "sdc/lnum_simple.ept")
ADD_TEST(compile_sdc_run_modular "scripts/compile_sdc_run" "sdc/modular.ept")
ADD_TEST(compile_sdc_run_office "scripts/compile_sdc_run" "sdc/office.ept")
ADD_TEST(compile_sdc_run_optim "scripts/compile_sdc_run" "sdc/optim.ept")
ADD_TEST(compile_sdc_run_radiotrans "scripts/compile_sdc_run" "sdc/radiotrans.ept")
ADD_TEST(compile_sdc_run_servers "scripts/compile_sdc_run" "sdc/servers.ept")
ADD_TEST(compile_sdc_run_tracking "scripts/compile_sdc_run" "sdc/tracking.ept")
