#!/bin/bash

for i in bad/*.ept; do
    echo 'ADD_TEST(compile_fail_'`basename $i .ept` '"scripts/compile_fail"' '"'$i'" "-memalloc")'
done

for i in good/*.ept; do
    echo 'ADD_TEST(compile_only_'`basename $i .ept` '"scripts/compile_only"' '"'$i'")'
done

for i in good/*.ept; do
    echo 'ADD_TEST(compile_gcc_run_'`basename $i .ept` '"scripts/compile_gcc_run"' '"'$i'")'
done


function compile_diff () {
    
    option=$1

    for i in good/*.ept; do
        echo "ADD_TEST(test_option_${option}_`basename $i .ept`" '"scripts/test_option"' '"'$i'"' '"-'$option'")'
    done

}

compile_diff "bool"
compile_diff "deadcode"
compile_diff "tomato"
compile_diff "flatten"
compile_diff "itfusion"
compile_diff "memalloc"
compile_diff "unroll"
compile_diff "O"

for i in good/*.ept; do
    name=`basename $i .ept`
    echo "ADD_TEST(compile_javac_run_${name} \"scripts/compile_javac_run\" \"${i}\")"
done

for i in sdc/*.ept; do
    name=`basename $i .ept`
    echo "ADD_TEST(compile_sdc_run_${name} \"scripts/compile_sdc_run\" \"${i}\")"
done
