//--------------------------------------------------------------------------------
// Auto-generated by LiteX (e6c63abe2) on 2025-04-01 14:36:33
//--------------------------------------------------------------------------------
#ifndef __GENERATED_MEM_H
#define __GENERATED_MEM_H

#ifndef SRAM_BASE
#define SRAM_BASE 0x01000000L
#define SRAM_SIZE 0x00002000
#endif

#ifndef CSR_BASE
#define CSR_BASE 0x00000000L
#define CSR_SIZE 0x00010000
#endif

#ifndef MEM_REGIONS
#define MEM_REGIONS "SRAM  0x01000000 0x2000 \nCSR   0x00000000 0x10000 "
#endif
#endif
