//--------------------------------------------------------------------------------
// Auto-generated by LiteX (e6c63abe2) on 2025-04-01 14:36:33
//--------------------------------------------------------------------------------
#ifndef __GENERATED_SOC_H
#define __GENERATED_SOC_H
#define CONFIG_PLATFORM_NAME "litex_m2sdr_platform"
#define CONFIG_CLOCK_FREQUENCY 125000000
#define CONFIG_CPU_TYPE_NONE
#define CONFIG_CPU_VARIANT_STANDARD
#define CONFIG_CPU_FAMILY
#define CONFIG_CPU_NAME
#define CONFIG_CPU_HUMAN_NAME "Unknown"
#define CONFIG_IDENTIFIER "LiteX-M2SDR SoC / baseboard variant / built on 2025-04-01 14:33:27"
#define UART_POLLING
#define CONFIG_FLASH_IMAGE_SIZE 8388608
#define CONFIG_CSR_DATA_WIDTH 32
#define CONFIG_CSR_ALIGNMENT 32
#define CONFIG_BUS_STANDARD "wishbone"
#define CONFIG_BUS_DATA_WIDTH 32
#define CONFIG_BUS_ADDRESS_WIDTH 32
#define CONFIG_BUS_BURSTING 0

#endif
